/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import rojerusan.RSNotifyFade;

/**
 *
 * @author SailorSakura
 */
public class Caja extends javax.swing.JInternalFrame {
    DecimalFormat formateador = new DecimalFormat("#,##0.###");
    
    public Caja() {
         initComponents();
        funciones.funcionesCaja.setListarPrueba("");
        funciones.funcionesCaja.setListarVentas("");
        idCaja.setText(funciones.funcionesCaja.extraerIDMaxCaja());
        funciones.funcionesIngresoEgreso.setListarEgresos(FechaActual());
        funciones.funcionesIngresoEgreso.setListarIngresos(FechaActual());
        
        CalcularTotales();
        
        dateSeleccion.setText(FechaActual());
        botonCierre.setEnabled(false);
        botonNuevoEgreso.setEnabled(false);
        botonNuevoIngreso.setEnabled(false);
        idCaja.setVisible(false);
        idC.setVisible(false);
        
        idC.setText(idPrincipal);
        lblCuenta.setText(lblPrincipal);
        txtSaldo.setText(txtPrincipal);
        
        if(vistas.Principal.txtSaldoPrincipal.getText().length() == 0){
           // System.out.println("pasa el if");
           
        } else {
            vistas.Caja.botonApertura.setVisible(false);
            vistas.Caja.botonCierre.setEnabled(true);
            vistas.Caja.botonNuevoEgreso.setEnabled(true);
            vistas.Caja.botonNuevoIngreso.setEnabled(true);
        }
        
    }
    String idPrincipal = vistas.Principal.idCuentaPrincipal.getText();
    String lblPrincipal = vistas.Principal.lblCuentaPrincipal.getText();
    String txtPrincipal = vistas.Principal.txtSaldoPrincipal.getText();
    
public static String FechaActual(){
    Date fecha = new Date();
    SimpleDateFormat formatofecha= new SimpleDateFormat("dd/MM/yyyy");
    return formatofecha.format(fecha);
}

public void CalcularTotales(){
    int totalCompras = 0, totalVentas = 0, totalGen = 0;
    int sumaCompras = 0, sumasVentas = 0, totalIng = 0, totalEgr = 0, sumasIng = 0, sumasEgr = 0;
    for (int i = 0; i < tablaComprasCaja.getRowCount(); i++) {
        totalCompras = Integer.parseInt(tablaComprasCaja.getValueAt(i,1).toString());
        sumaCompras += totalCompras;
    }
    for (int i = 0; i < tablaVentasCaja.getRowCount(); i++) {
       totalVentas = Integer.parseInt(tablaVentasCaja.getValueAt(i,2).toString());
       sumasVentas += totalVentas; 
    }
     for (int i = 0; i < tablaIngresosCaja.getRowCount(); i++) {
       totalIng = Integer.parseInt(tablaIngresosCaja.getValueAt(i,1).toString());
       sumasIng += totalIng; 
    }
     for (int i = 0; i < tablaEgresosCaja.getRowCount(); i++) {
       totalEgr = Integer.parseInt(tablaEgresosCaja.getValueAt(i,1).toString());
       sumasEgr += totalEgr; 
    }
    
    totalGen = (sumasVentas + sumasIng) - (sumasEgr + sumaCompras);
    
    
    
    
     txtTotalGenCompras.setText(String.valueOf(sumaCompras));
     txtTotalGenVentas.setText(String.valueOf(sumasVentas));
     txtIngreso.setText(String.valueOf(sumasIng));
     txtEgreso.setText(String.valueOf(sumasEgr));
     txtTotalCierre.setText(String.valueOf(totalGen));
    
    
    String puntocompra = String.valueOf(sumaCompras);
    String puntoventa = String.valueOf(sumasVentas);
    String puntoegreso = String.valueOf(sumasEgr);
    String puntoingreso = String.valueOf(sumasIng);
    String puntocierre = String.valueOf(totalGen);
    
        if(puntocompra.length() > 3){
            String cadena = puntocompra.replace(".","");
            txtTotalGenCompras.setText(formateador.format(Integer.parseInt(cadena)));
        } 
        if(puntoventa.length() > 3){
            String cadena2 = puntoventa.replace(".","");
            txtTotalGenVentas.setText(formateador.format(Integer.parseInt(cadena2)));
        }
        if(puntoegreso.length() > 3){
            String cadena3 = puntoegreso.replace(".","");
            txtEgreso.setText(formateador.format(Integer.parseInt(cadena3)));
        }
        if(puntoingreso.length() > 3){
            String cadena4 = puntoingreso.replace(".","");
            txtIngreso.setText(formateador.format(Integer.parseInt(cadena4)));
        }
        if(puntocierre.length() > 3){
            String cadena5 = puntocierre.replace(".","");
            txtTotalCierre.setText(formateador.format(Integer.parseInt(cadena5)));
        }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaComprasCaja = new rojerusan.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalGenCompras = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTotalGenVentas = new javax.swing.JTextField();
        txtEgreso = new javax.swing.JTextField();
        txtIngreso = new javax.swing.JTextField();
        botonNuevoIngreso = new rojerusan.RSButtonHover();
        botonNuevoEgreso = new rojerusan.RSButtonHover();
        botonApertura = new rojerusan.RSButtonHover();
        botonCierre = new rojerusan.RSButtonHover();
        jLabel9 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        lblCuenta = new javax.swing.JLabel();
        dateSeleccion = new javax.swing.JTextField();
        idC = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaVentasCaja = new rojerusan.RSTableMetro();
        idCaja = new javax.swing.JLabel();
        txtTotalCierre = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaIngresosCaja = new rojerusan.RSTableMetro();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaEgresosCaja = new rojerusan.RSTableMetro();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaComprasCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaComprasCaja.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaComprasCaja.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaComprasCaja.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaComprasCaja.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane1.setViewportView(tablaComprasCaja);
        if (tablaComprasCaja.getColumnModel().getColumnCount() > 0) {
            tablaComprasCaja.getColumnModel().getColumn(0).setMinWidth(0);
            tablaComprasCaja.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 167, 387, 167));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CAJA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Compras");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 132, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ventas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 132, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Total General:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 362, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-cerrar2.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, -1, -1));

        txtTotalGenCompras.setEditable(false);
        txtTotalGenCompras.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalGenCompras.setText("0");
        jPanel1.add(txtTotalGenCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 352, 135, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Total General:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(898, 360, -1, -1));

        txtTotalGenVentas.setEditable(false);
        txtTotalGenVentas.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalGenVentas.setText("0");
        jPanel1.add(txtTotalGenVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 350, 135, 40));

        txtEgreso.setEditable(false);
        txtEgreso.setBackground(new java.awt.Color(255, 255, 255));
        txtEgreso.setText("0");
        jPanel1.add(txtEgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 636, 133, 40));

        txtIngreso.setEditable(false);
        txtIngreso.setBackground(new java.awt.Color(255, 255, 255));
        txtIngreso.setText("0");
        jPanel1.add(txtIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 636, 133, 40));

        botonNuevoIngreso.setBackground(new java.awt.Color(11, 11, 11));
        botonNuevoIngreso.setText("Registrar ingreso");
        botonNuevoIngreso.setColorHover(new java.awt.Color(240, 4, 7));
        botonNuevoIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoIngresoActionPerformed(evt);
            }
        });
        jPanel1.add(botonNuevoIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 378, 180, -1));

        botonNuevoEgreso.setBackground(new java.awt.Color(11, 11, 11));
        botonNuevoEgreso.setText("Registrar egreso");
        botonNuevoEgreso.setColorHover(new java.awt.Color(240, 4, 7));
        botonNuevoEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoEgresoActionPerformed(evt);
            }
        });
        jPanel1.add(botonNuevoEgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 180, -1));

        botonApertura.setBackground(new java.awt.Color(11, 11, 11));
        botonApertura.setText("Apertura");
        botonApertura.setColorHover(new java.awt.Color(240, 4, 7));
        botonApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAperturaActionPerformed(evt);
            }
        });
        jPanel1.add(botonApertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 180, -1));

        botonCierre.setBackground(new java.awt.Color(11, 11, 11));
        botonCierre.setText("Cierre del día");
        botonCierre.setColorHover(new java.awt.Color(240, 4, 7));
        botonCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCierreActionPerformed(evt);
            }
        });
        jPanel1.add(botonCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 180, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Saldo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 177, -1, -1));

        txtSaldo.setEditable(false);
        txtSaldo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 167, 180, 40));

        lblCuenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCuenta.setText("lblCuenta");
        jPanel1.add(lblCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 139, 257, -1));

        dateSeleccion.setEditable(false);
        dateSeleccion.setBackground(new java.awt.Color(255, 255, 255));
        dateSeleccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(dateSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 59, 200, 40));

        idC.setText("IdC");
        jPanel1.add(idC, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 245, -1, -1));

        tablaVentasCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentasCaja.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaVentasCaja.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaVentasCaja.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaVentasCaja.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane3.setViewportView(tablaVentasCaja);
        if (tablaVentasCaja.getColumnModel().getColumnCount() > 0) {
            tablaVentasCaja.getColumnModel().getColumn(0).setMinWidth(0);
            tablaVentasCaja.getColumnModel().getColumn(0).setMaxWidth(0);
            tablaVentasCaja.getColumnModel().getColumn(1).setMinWidth(120);
            tablaVentasCaja.getColumnModel().getColumn(1).setMaxWidth(120);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 383, 167));

        idCaja.setText("idCaja");
        jPanel1.add(idCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 75, -1, -1));

        txtTotalCierre.setEditable(false);
        txtTotalCierre.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalCierre.setText("0");
        jPanel1.add(txtTotalCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 180, 40));

        tablaIngresosCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Monto", "Concepto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaIngresosCaja.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaIngresosCaja.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaIngresosCaja.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaIngresosCaja.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane4.setViewportView(tablaIngresosCaja);
        if (tablaIngresosCaja.getColumnModel().getColumnCount() > 0) {
            tablaIngresosCaja.getColumnModel().getColumn(0).setMinWidth(0);
            tablaIngresosCaja.getColumnModel().getColumn(0).setMaxWidth(0);
            tablaIngresosCaja.getColumnModel().getColumn(1).setMinWidth(120);
            tablaIngresosCaja.getColumnModel().getColumn(1).setMaxWidth(120);
        }

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 446, 387, 167));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Total General:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 646, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Ingresos");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 416, -1, -1));

        tablaEgresosCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Monto", "Concepto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEgresosCaja.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaEgresosCaja.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaEgresosCaja.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaEgresosCaja.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane5.setViewportView(tablaEgresosCaja);
        if (tablaEgresosCaja.getColumnModel().getColumnCount() > 0) {
            tablaEgresosCaja.getColumnModel().getColumn(0).setMinWidth(0);
            tablaEgresosCaja.getColumnModel().getColumn(0).setMaxWidth(0);
            tablaEgresosCaja.getColumnModel().getColumn(1).setMinWidth(120);
            tablaEgresosCaja.getColumnModel().getColumn(1).setMaxWidth(120);
        }

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 446, 383, 167));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Total General:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 646, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Egresos");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 416, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1189, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void botonAperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAperturaActionPerformed
        Apertura f = new Apertura(new JFrame(), true);
        f.show();
    }//GEN-LAST:event_botonAperturaActionPerformed

    private void botonNuevoIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoIngresoActionPerformed
        RegistrarIngresos f = new RegistrarIngresos(new JFrame(), true);
        f.show();
        CalcularTotales();
    }//GEN-LAST:event_botonNuevoIngresoActionPerformed

    private void botonNuevoEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoEgresoActionPerformed
       RegistrarEgresos f = new RegistrarEgresos(new JFrame(), true);
        f.show();
        CalcularTotales();
    }//GEN-LAST:event_botonNuevoEgresoActionPerformed

    private void botonCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCierreActionPerformed
        String cierre3 = librerias.SeparadorMiles.quitarPuntos(vistas.Caja.txtTotalCierre.getText());
        int cierre2 = Integer.parseInt(cierre3);
        if (cierre2 > 0) {
            String cierre = vistas.Caja.txtTotalCierre.getText();
            String fec = vistas.Caja.dateSeleccion.getText();
            String account = vistas.Caja.lblCuenta.getText();
            String number = vistas.Caja.idC.getText();
            String idcaja = vistas.Caja.idCaja.getText();
            
            String apertura = librerias.SeparadorMiles.quitarPuntos(vistas.Caja.txtSaldo.getText());
            
            
            int total = 0;
            total = cierre2 + Integer.parseInt(apertura);
            funciones.funcionesCaja.guardarCaja();
            this.dispose();
            Movimientos f = new Movimientos(new JFrame(), true);
            
            String puntomov = String.valueOf(total);
            if(puntomov.length() > 3){
            String cadena6 = puntomov.replace(".","");
            f.txtMontoMov.setText(formateador.format(Integer.parseInt(cadena6)));
        }
           // f.txtMontoMov.setText(Integer.valueOf(total).toString());
            f.txtCuentaMov.setText(account);
            f.txtFechaMov.setText(fec);
            f.idCajaMov.setText(idcaja);
            f.idCuentaMov.setText(number);
            f.show();
        } else {
            new rojerusan.RSNotifyFade("ERROR", "No se puede realizar el cierre", 5, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.ERROR).setVisible(true);
        }
        
    }//GEN-LAST:event_botonCierreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static rojerusan.RSButtonHover botonApertura;
    public static rojerusan.RSButtonHover botonCierre;
    public static rojerusan.RSButtonHover botonNuevoEgreso;
    public static rojerusan.RSButtonHover botonNuevoIngreso;
    public static javax.swing.JTextField dateSeleccion;
    public static javax.swing.JLabel idC;
    public static javax.swing.JLabel idCaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JLabel lblCuenta;
    public static rojerusan.RSTableMetro tablaComprasCaja;
    public static rojerusan.RSTableMetro tablaEgresosCaja;
    public static rojerusan.RSTableMetro tablaIngresosCaja;
    public static rojerusan.RSTableMetro tablaVentasCaja;
    public static javax.swing.JTextField txtEgreso;
    public static javax.swing.JTextField txtIngreso;
    public static javax.swing.JTextField txtSaldo;
    public static javax.swing.JTextField txtTotalCierre;
    public static javax.swing.JTextField txtTotalGenCompras;
    public static javax.swing.JTextField txtTotalGenVentas;
    // End of variables declaration//GEN-END:variables
}
