/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import funciones.sentenciasFuncionarios;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import rojerusan.RSNotifyAnimated;

/**
 *
 * @author SailorSakura
 */
public class Funcionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Funcionarios
     */
    public Funcionarios() {
        initComponents();
        funciones.funcionesFuncionarios.setListar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonAgregarFuncionario = new rojerusan.RSButtonHover();
        botonModificarFuncionario = new rojerusan.RSButtonHover();
        botonEliminarFuncionario = new rojerusan.RSButtonHover();
        txtBuscarFuncionarios = new rojerusan.RSMetroTextFullPlaceHolder();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaFuncionarios = new rojerusan.RSTableMetro();

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName(""); // NOI18N

        botonAgregarFuncionario.setBackground(new java.awt.Color(11, 11, 11));
        botonAgregarFuncionario.setText("Agregar Funcionario");
        botonAgregarFuncionario.setColorHover(new java.awt.Color(240, 4, 7));
        botonAgregarFuncionario.setMaximumSize(new java.awt.Dimension(91, 25));
        botonAgregarFuncionario.setMinimumSize(new java.awt.Dimension(91, 25));
        botonAgregarFuncionario.setName("botonAgregarFuncionario"); // NOI18N
        botonAgregarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarFuncionarioActionPerformed(evt);
            }
        });

        botonModificarFuncionario.setBackground(new java.awt.Color(11, 11, 11));
        botonModificarFuncionario.setText("Modificar Funcionario");
        botonModificarFuncionario.setColorHover(new java.awt.Color(240, 4, 7));
        botonModificarFuncionario.setMaximumSize(new java.awt.Dimension(91, 25));
        botonModificarFuncionario.setMinimumSize(new java.awt.Dimension(91, 25));
        botonModificarFuncionario.setName("botonModificarFuncionario"); // NOI18N
        botonModificarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarFuncionarioActionPerformed(evt);
            }
        });

        botonEliminarFuncionario.setBackground(new java.awt.Color(11, 11, 11));
        botonEliminarFuncionario.setText("Eliminar Funcionario");
        botonEliminarFuncionario.setColorHover(new java.awt.Color(240, 4, 7));
        botonEliminarFuncionario.setMaximumSize(new java.awt.Dimension(91, 25));
        botonEliminarFuncionario.setMinimumSize(new java.awt.Dimension(91, 25));
        botonEliminarFuncionario.setName("botonEliminarFuncionario"); // NOI18N
        botonEliminarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarFuncionarioActionPerformed(evt);
            }
        });

        txtBuscarFuncionarios.setForeground(new java.awt.Color(11, 11, 11));
        txtBuscarFuncionarios.setBorderColor(new java.awt.Color(11, 11, 11));
        txtBuscarFuncionarios.setBotonColor(new java.awt.Color(240, 4, 7));
        txtBuscarFuncionarios.setName("txtBuscarFuncionarios"); // NOI18N
        txtBuscarFuncionarios.setPhColor(new java.awt.Color(0, 0, 0));
        txtBuscarFuncionarios.setPlaceholder("");
        txtBuscarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarFuncionariosActionPerformed(evt);
            }
        });
        txtBuscarFuncionarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarFuncionariosKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Buscar:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-cerrar2.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("LISTADO DE FUNCIONARIOS");

        tablaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nombre y Apellido", "RUC o CI", "Ciudad", "Correo", "Telefono", "Direccion", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaFuncionarios.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaFuncionarios.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaFuncionarios.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaFuncionarios.setName("tablaFuncionarios"); // NOI18N
        tablaFuncionarios.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane2.setViewportView(tablaFuncionarios);
        if (tablaFuncionarios.getColumnModel().getColumnCount() > 0) {
            tablaFuncionarios.getColumnModel().getColumn(0).setResizable(false);
            tablaFuncionarios.getColumnModel().getColumn(1).setResizable(false);
            tablaFuncionarios.getColumnModel().getColumn(2).setResizable(false);
            tablaFuncionarios.getColumnModel().getColumn(3).setResizable(false);
            tablaFuncionarios.getColumnModel().getColumn(4).setResizable(false);
            tablaFuncionarios.getColumnModel().getColumn(5).setResizable(false);
            tablaFuncionarios.getColumnModel().getColumn(6).setResizable(false);
            tablaFuncionarios.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel2)
                .addGap(141, 245, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAgregarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonModificarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarFuncionarioActionPerformed
        AgregarFuncionario b = new AgregarFuncionario(new JFrame(), true);
        b.show();
    }//GEN-LAST:event_botonAgregarFuncionarioActionPerformed

    private void txtBuscarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarFuncionariosActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void botonModificarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarFuncionarioActionPerformed
        int fila2 = tablaFuncionarios.getSelectedRow();
        if (fila2 > -1){
        int fila = tablaFuncionarios.getSelectedRow();
        Frame f = JOptionPane.getFrameForComponent(this);
        ModificarFuncionario dialog = new ModificarFuncionario(f, true);
        dialog.txtNombreFuncionario.setText(tablaFuncionarios.getValueAt(fila, 1).toString());
        dialog.txtRUCCI.setText(tablaFuncionarios.getValueAt(fila, 2).toString());
        dialog.comboCiudadUpdate.setSelectedItem(tablaFuncionarios.getValueAt(fila, 3).toString());
        dialog.txtCorreo.setText(tablaFuncionarios.getValueAt(fila, 4).toString());
        dialog.txtTelefono.setText(tablaFuncionarios.getValueAt(fila, 5).toString());
        dialog.txtDireccion.setText(tablaFuncionarios.getValueAt(fila, 6).toString());
        dialog.txtCargo.setText(tablaFuncionarios.getValueAt(fila, 7).toString());
        dialog.txtIdFuncionario.setText(tablaFuncionarios.getValueAt(fila, 0).toString());
        dialog.show();
        } else {
            new rojerusan.RSNotifyAnimated("ERROR", "Seleccione un funcionario", 5, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);

        }
    }//GEN-LAST:event_botonModificarFuncionarioActionPerformed
String hora = "";
String fecha= "";
    private void botonEliminarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarFuncionarioActionPerformed
            String tabla = "FUNCIONARIO";
            String evento = "DELETE";
            hora = Principal.lblhora.getHora();
            fecha = Principal.lblfecha.getFecha();
        int fila3 = tablaFuncionarios.getSelectedRow();
        if (fila3 > -1){
        int fila = tablaFuncionarios.getSelectedRow();
        sentenciasFuncionarios s = new sentenciasFuncionarios();
        s.setId_funcionario(tablaFuncionarios.getValueAt(fila, 0).toString());
        if (JOptionPane.showConfirmDialog(this, "Desea eliminar registro?", "",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
            if (funciones.funcionesFuncionarios.isDelete(s)){
                funciones.funcionesFuncionarios.extraerIDMaxFUN();
                new rojerusan.RSNotifyAnimated("EXITO", "Se ha eliminado", 5, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
                funciones.funcionesFuncionarios.setListar("");
                funciones.funcionesAuditoria.auditoria(fecha, hora, evento, tabla, login.funcionesLogin.idFuncionario);
            }
        }
        } else {
            new rojerusan.RSNotifyAnimated("ERROR", "Seleccione uno", 5, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);

        }
    }//GEN-LAST:event_botonEliminarFuncionarioActionPerformed

    private void txtBuscarFuncionariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarFuncionariosKeyReleased
        librerias.Mayusculas.convertiraMayusculasEnJtextfield(txtBuscarFuncionarios);
        funciones.funcionesFuncionarios.setListar(txtBuscarFuncionarios.getText());
    }//GEN-LAST:event_txtBuscarFuncionariosKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover botonAgregarFuncionario;
    private rojerusan.RSButtonHover botonEliminarFuncionario;
    private rojerusan.RSButtonHover botonModificarFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static rojerusan.RSTableMetro tablaFuncionarios;
    private rojerusan.RSMetroTextFullPlaceHolder txtBuscarFuncionarios;
    // End of variables declaration//GEN-END:variables
}
