/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import funciones.sentenciasOrdenCompra;
import java.awt.Frame;
import javax.swing.JOptionPane;
import rojerusan.RSNotifyAnimated;

/**
 *
 * @author SailorSakura
 */
public class ListadoOrdenCompra extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListadoOrdenCompra
     */
    public ListadoOrdenCompra() {
        initComponents();
        funciones.funcionesOrdenCompra.setListarOrdenCompra();
        rSPopuMenu1.add(Ver);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSLabelVerticalD1 = new rojerusan.RSLabelVerticalD();
        rSPopuMenu1 = new rojerusan.RSPopuMenu();
        Ver = new javax.swing.JPanel();
        botonVer = new rojerusan.RSButtonHover();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListadoOC = new rojerusan.RSTableMetro();
        jLabel2 = new javax.swing.JLabel();
        botonRegistrarOC = new rojerusan.RSButtonHover();
        botonEliminarOC = new rojerusan.RSButtonHover();
        botonRegistrarCompra = new rojerusan.RSButtonHover();

        rSLabelVerticalD1.setText("rSLabelVerticalD1");

        Ver.setBackground(new java.awt.Color(255, 255, 255));

        botonVer.setBackground(new java.awt.Color(11, 11, 11));
        botonVer.setText("Ver detalles");
        botonVer.setColorHover(new java.awt.Color(240, 4, 7));
        botonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VerLayout = new javax.swing.GroupLayout(Ver);
        Ver.setLayout(VerLayout);
        VerLayout.setHorizontalGroup(
            VerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VerLayout.setVerticalGroup(
            VerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-cerrar2.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        tablaListadoOC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Proveedor", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaListadoOC.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaListadoOC.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaListadoOC.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaListadoOC.setComponentPopupMenu(rSPopuMenu1);
        tablaListadoOC.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane1.setViewportView(tablaListadoOC);
        if (tablaListadoOC.getColumnModel().getColumnCount() > 0) {
            tablaListadoOC.getColumnModel().getColumn(0).setMinWidth(0);
            tablaListadoOC.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("LISTADO DE ORDENES DE COMPRAS");

        botonRegistrarOC.setBackground(new java.awt.Color(11, 11, 11));
        botonRegistrarOC.setText("Registrar Orden");
        botonRegistrarOC.setColorHover(new java.awt.Color(240, 4, 7));
        botonRegistrarOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarOCActionPerformed(evt);
            }
        });

        botonEliminarOC.setBackground(new java.awt.Color(11, 11, 11));
        botonEliminarOC.setText("Finalizar Orden");
        botonEliminarOC.setColorHover(new java.awt.Color(240, 4, 7));
        botonEliminarOC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarOCActionPerformed(evt);
            }
        });

        botonRegistrarCompra.setBackground(new java.awt.Color(11, 11, 11));
        botonRegistrarCompra.setText("Registrar Compra");
        botonRegistrarCompra.setColorHover(new java.awt.Color(240, 4, 7));
        botonRegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonRegistrarOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonRegistrarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(157, 157, 157))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrarOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarOC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegistrarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void botonRegistrarOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarOCActionPerformed
        RegistrarOrdenCompra p = new RegistrarOrdenCompra();
        vistas.Principal.jDesktopPane1.add(p);
        p.setVisible(true);
        p.setUI(null);
        librerias.UtilitariosFrame.centrarInternalFrame(vistas.Principal.jDesktopPane1, p);
       this.dispose();
    }//GEN-LAST:event_botonRegistrarOCActionPerformed

    private void botonRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarCompraActionPerformed
        
        int fila = tablaListadoOC.getSelectedRow();
        if (fila != -1){
            RegistrarCompra p = new RegistrarCompra();
            vistas.Principal.jDesktopPane1.add(p);
            funciones.funcionesCompras.setListarListado(tablaListadoOC.getValueAt(fila, 0).toString());
            System.out.println("pasa id orden"+tablaListadoOC.getValueAt(fila, 0).toString());
            RegistrarCompra.txtProveedor.setText(tablaListadoOC.getValueAt(fila, 2).toString());
            RegistrarCompra.idOrden.setText(tablaListadoOC.getValueAt(fila, 0).toString());
            p.setVisible(true);
            p.setUI(null);
            librerias.UtilitariosFrame.centrarInternalFrame(vistas.Principal.jDesktopPane1, p);
        } else {
            new rojerusan.RSNotifyAnimated("ERROR", "Seleccione uno", 5, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
        }
        
        
       
    }//GEN-LAST:event_botonRegistrarCompraActionPerformed

    private void botonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerActionPerformed
        Frame f = JOptionPane.getFrameForComponent(this);
        VerDetalleOrden dialog = new VerDetalleOrden(f, true);
        int fila = tablaListadoOC.getSelectedRow();
        if (fila != -1){
            funciones.funcionesOrdenCompra.mostrarDetallesOrden(tablaListadoOC.getValueAt(fila, 0).toString());
            dialog.show();
            
        } else {
            new rojerusan.RSNotifyAnimated("ERROR", "Seleccione uno", 5, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
        }
    }//GEN-LAST:event_botonVerActionPerformed

    private void botonEliminarOCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarOCActionPerformed
        int fila = tablaListadoOC.getSelectedRow();
        if (fila != -1){
        funciones.funcionesOrdenCompra.FinalizarOrden(tablaListadoOC.getValueAt(fila, 0).toString());
        funciones.funcionesOrdenCompra.setListarOrdenCompra();
        this.dispose();
        } else {
            new rojerusan.RSNotifyAnimated("ERROR", "Seleccione uno", 5, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
        }
    }//GEN-LAST:event_botonEliminarOCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ver;
    private rojerusan.RSButtonHover botonEliminarOC;
    private rojerusan.RSButtonHover botonRegistrarCompra;
    private rojerusan.RSButtonHover botonRegistrarOC;
    private rojerusan.RSButtonHover botonVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSLabelVerticalD rSLabelVerticalD1;
    private rojerusan.RSPopuMenu rSPopuMenu1;
    public static rojerusan.RSTableMetro tablaListadoOC;
    // End of variables declaration//GEN-END:variables
}
