/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import conexion.Conexion;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import rojerusan.RSNotifyAnimated;
import rojerusan.RSNotifyFade;

/**
 *
 * @author SailorSakura
 */
public class ListadoCompras extends javax.swing.JInternalFrame {
    private static   Conexion conexion = new Conexion();
    private static   Connection conexionActual = conexion.conectar();
    private static PreparedStatement ps= null;
    /**
     * Creates new form ListadoCompras
     */
    public ListadoCompras() {
        initComponents();
        funciones.funcionesCompras.setListarCompras();
        rSPopuMenu1.add(Opciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPopuMenu1 = new rojerusan.RSPopuMenu();
        Opciones = new javax.swing.JPanel();
        Ver = new javax.swing.JPanel();
        botonVer = new rojerusan.RSButtonHover();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListadoC = new rojerusan.RSTableMetro();
        jLabel2 = new javax.swing.JLabel();
        filtroFecha = new rojerusan.RSDateChooser();
        botonReporte = new rojerusan.RSButtonHover();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonfiltro = new rojerusan.RSButtonHover();
        fechaDesde = new javax.swing.JFormattedTextField();
        fechaHasta = new javax.swing.JFormattedTextField();

        Ver.setBackground(new java.awt.Color(255, 255, 255));

        botonVer.setBackground(new java.awt.Color(11, 11, 11));
        botonVer.setText("Ver detalles");
        botonVer.setColorHover(new java.awt.Color(240, 4, 7));
        botonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VerLayout = new javax.swing.GroupLayout(Ver);
        Ver.setLayout(VerLayout);
        VerLayout.setHorizontalGroup(
            VerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VerLayout.setVerticalGroup(
            VerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout OpcionesLayout = new javax.swing.GroupLayout(Opciones);
        Opciones.setLayout(OpcionesLayout);
        OpcionesLayout.setHorizontalGroup(
            OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        OpcionesLayout.setVerticalGroup(
            OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-cerrar2.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 18, -1, -1));

        tablaListadoC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Timbrado", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaListadoC.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaListadoC.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaListadoC.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaListadoC.setComponentPopupMenu(rSPopuMenu1);
        tablaListadoC.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane1.setViewportView(tablaListadoC);
        if (tablaListadoC.getColumnModel().getColumnCount() > 0) {
            tablaListadoC.getColumnModel().getColumn(0).setMinWidth(0);
            tablaListadoC.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 159, 522, 202));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("LISTADO DE COMPRAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 61, -1, -1));

        filtroFecha.setForeground(new java.awt.Color(11, 11, 11));
        filtroFecha.setColorBackground(new java.awt.Color(11, 11, 11));
        filtroFecha.setColorButtonHover(new java.awt.Color(240, 4, 7));
        filtroFecha.setColorDiaActual(new java.awt.Color(240, 4, 7));
        filtroFecha.setFormatoFecha("dd/MM/yyyy");
        filtroFecha.setPlaceholder("");
        jPanel1.add(filtroFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 200, -1));

        botonReporte.setBackground(new java.awt.Color(11, 11, 11));
        botonReporte.setText("Ver reporte");
        botonReporte.setColorHover(new java.awt.Color(240, 4, 7));
        botonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteActionPerformed(evt);
            }
        });
        jPanel1.add(botonReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, -1, -1));

        jLabel3.setText("Para ver los reportes entre fechas que desea, por favor selecione:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 399, -1, -1));

        jLabel4.setText("Desde:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 439, -1, -1));

        jLabel5.setText("Hasta:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 489, -1, -1));

        jLabel6.setText("Filtrar:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        botonfiltro.setBackground(new java.awt.Color(255, 255, 255));
        botonfiltro.setBorder(null);
        botonfiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa-para-buscar.png"))); // NOI18N
        botonfiltro.setColorHover(new java.awt.Color(240, 4, 7));
        botonfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonfiltroActionPerformed(evt);
            }
        });
        jPanel1.add(botonfiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 40, 40));

        try {
            fechaDesde.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechaDesde.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(fechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 130, 30));

        try {
            fechaHasta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechaHasta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(fechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void botonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerActionPerformed
        Frame f = JOptionPane.getFrameForComponent(this);
        VerDetalleCompra dialog = new VerDetalleCompra(f, true);
        int fila = tablaListadoC.getSelectedRow();
        if (fila != -1){
            funciones.funcionesCompras.mostrarDetallesCompra(tablaListadoC.getValueAt(fila, 0).toString());
            dialog.show();

        } else {
            new rojerusan.RSNotifyAnimated("ERROR", "Seleccione uno", 5, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
        }
    }//GEN-LAST:event_botonVerActionPerformed

    private void botonfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonfiltroActionPerformed
        funciones.funcionesCompras.setFiltrarCompras();
    }//GEN-LAST:event_botonfiltroActionPerformed

    private void botonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteActionPerformed
        if (fechaDesde.getText().length()==0 || fechaHasta.getText().length()== 0) {
            new rojerusan.RSNotifyFade("ADVERTENCIA", "Ingrese las fechas", 5, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.WARNING).setVisible(true);
        } else {
            try {
            JasperReport jr = (JasperReport) JRLoader.loadObject(getClass().getResource("/reportes/Compras.jasper"));
            
            Map parametro = new HashMap();
                parametro.put("FechaAnt", fechaDesde.getText()); 
                parametro.put("FechaActu", fechaHasta.getText());
                parametro.put("IMAGEN", getClass().getResourceAsStream("/imagenes/FacturaProducto.png"));
            JasperPrint jp = JasperFillManager.fillReport(jr, parametro, conexionActual);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            jv.setTitle("Reporte de Compras");
        } catch (JRException ex) {
             System.err.println("Error: "+ex.getMessage());
    }
        }
        
    }//GEN-LAST:event_botonReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Opciones;
    private javax.swing.JPanel Ver;
    private rojerusan.RSButtonHover botonReporte;
    private rojerusan.RSButtonHover botonVer;
    private rojerusan.RSButtonHover botonfiltro;
    public static javax.swing.JFormattedTextField fechaDesde;
    public static javax.swing.JFormattedTextField fechaHasta;
    public static rojerusan.RSDateChooser filtroFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSPopuMenu rSPopuMenu1;
    public static rojerusan.RSTableMetro tablaListadoC;
    // End of variables declaration//GEN-END:variables
}
