/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import conexion.Conexion;
import funciones.funcionesPaises;
import funciones.sentenciasPaises;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import rojerusan.RSNotifyFade;

/**
 *
 * @author SailorSakura
 */
public class Paises extends javax.swing.JInternalFrame {

    /**
     * Creates new form Paises
     */
    public Paises() {
        initComponents();
        funcionesPaises.setListar("");
        this.idPais.setText(funciones.funcionesPaises.extraerIDMaxPAIS());
        idPais.setVisible(false);
    }
    Conexion conexion = new Conexion();
    Connection conexionActual = conexion.conectar();
    PreparedStatement ps;
    ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evaluatorShort1 = new org.jdesktop.core.animation.timing.evaluators.EvaluatorShort();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPais = new rojerusan.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarPais = new rojerusan.RSMetroTextFullPlaceHolder();
        txtAgregarPais = new rojerusan.RSMetroTextFullPlaceHolder();
        botonAgregarPais = new rojerusan.RSButtonHover();
        botonModificarPais = new rojerusan.RSButtonHover();
        botonEliminarPais = new rojerusan.RSButtonHover();
        idPais = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("PAÍSES");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-cerrar2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        tablaPais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "País"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPais.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaPais.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaPais.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaPais.setName("tablaPais"); // NOI18N
        tablaPais.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane1.setViewportView(tablaPais);
        if (tablaPais.getColumnModel().getColumnCount() > 0) {
            tablaPais.getColumnModel().getColumn(0).setMinWidth(0);
            tablaPais.getColumnModel().getColumn(0).setMaxWidth(0);
            tablaPais.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel1.setText("Buscar:");

        txtBuscarPais.setForeground(new java.awt.Color(11, 11, 11));
        txtBuscarPais.setBorderColor(new java.awt.Color(11, 11, 11));
        txtBuscarPais.setBotonColor(new java.awt.Color(240, 4, 7));
        txtBuscarPais.setName("txtBuscarPais"); // NOI18N
        txtBuscarPais.setPhColor(new java.awt.Color(0, 0, 0));
        txtBuscarPais.setPlaceholder("");
        txtBuscarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPaisActionPerformed(evt);
            }
        });
        txtBuscarPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarPaisKeyReleased(evt);
            }
        });

        txtAgregarPais.setForeground(new java.awt.Color(11, 11, 11));
        txtAgregarPais.setBorderColor(new java.awt.Color(11, 11, 11));
        txtAgregarPais.setBotonColor(new java.awt.Color(240, 4, 7));
        txtAgregarPais.setName("txtAgregarPais"); // NOI18N
        txtAgregarPais.setPhColor(new java.awt.Color(0, 0, 0));
        txtAgregarPais.setPlaceholder("");
        txtAgregarPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgregarPaisKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgregarPaisKeyTyped(evt);
            }
        });

        botonAgregarPais.setBackground(new java.awt.Color(11, 11, 11));
        botonAgregarPais.setText("Agregar País");
        botonAgregarPais.setColorHover(new java.awt.Color(240, 4, 7));
        botonAgregarPais.setMaximumSize(new java.awt.Dimension(91, 25));
        botonAgregarPais.setMinimumSize(new java.awt.Dimension(91, 25));
        botonAgregarPais.setName("botonAgregarPais"); // NOI18N
        botonAgregarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPaisActionPerformed(evt);
            }
        });

        botonModificarPais.setBackground(new java.awt.Color(11, 11, 11));
        botonModificarPais.setText("Modificar País");
        botonModificarPais.setColorHover(new java.awt.Color(240, 4, 7));
        botonModificarPais.setMaximumSize(new java.awt.Dimension(91, 25));
        botonModificarPais.setMinimumSize(new java.awt.Dimension(91, 25));
        botonModificarPais.setName("botonModificarPais"); // NOI18N
        botonModificarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarPaisActionPerformed(evt);
            }
        });

        botonEliminarPais.setBackground(new java.awt.Color(11, 11, 11));
        botonEliminarPais.setText("Eliminar País");
        botonEliminarPais.setColorHover(new java.awt.Color(240, 4, 7));
        botonEliminarPais.setMaximumSize(new java.awt.Dimension(91, 25));
        botonEliminarPais.setMinimumSize(new java.awt.Dimension(91, 25));
        botonEliminarPais.setName("botonEliminarPais"); // NOI18N
        botonEliminarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPaisActionPerformed(evt);
            }
        });

        idPais.setText("ID");
        idPais.setName("idPais"); // NOI18N

        jLabel4.setText("Ingrese un nuevo:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 4, 7));
        jLabel6.setText("Para agregar un nuevo país, ingrese los siguientes datos:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(idPais)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(794, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonModificarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonEliminarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAgregarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonAgregarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(348, 348, 348))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(idPais))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonEliminarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonModificarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAgregarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAgregarPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(88, 88, 88)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPaisActionPerformed
          txtAgregarPais.requestFocus();
          if (txtAgregarPais.getText().length()==0) {
            new rojerusan.RSNotifyFade("ERROR", "Ingrese los datos solicitados", 5, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.ERROR).setVisible(true);
        } else {
          try{
        
        String sql= "INSERT INTO paises(id_pais,n_pais)"
                      +"VALUES('"+idPais.getText()+"','"+txtAgregarPais.getText()+"')";
    
              ps = conexionActual.prepareStatement(sql);
              
              int resultado = ps.executeUpdate();
              if (resultado > 0){
                  funcionesPaises.setListar("");
                 
                  this.idPais.setText(funcionesPaises.extraerIDMaxPAIS());
                  new rojerusan.RSNotifyFade("EXITO", "Se ha registrado", 5, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                  txtAgregarPais.setText("");
                  funciones.funcionesPaises.extraerIDMaxPAIS();
              }else{
                  new rojerusan.RSNotifyFade("ERROR", "Ha ocurrido un problema al registrar", 5, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.ERROR).setVisible(true);
              }
               } catch (Exception e) {
                  System.out.print("error"+e.getMessage());
          }
          }
    }//GEN-LAST:event_botonAgregarPaisActionPerformed
String hora = "";
String fecha= "";
    private void botonEliminarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPaisActionPerformed
         String tabla = "PAIS";
            String evento = "DELETE";
            hora = Principal.lblhora.getHora();
            fecha = Principal.lblfecha.getFecha();   
        int selec = tablaPais.getSelectedRow();
        if (selec >-1) {
            int fila = tablaPais.getSelectedRow();
            sentenciasPaises s = new sentenciasPaises();
            s.setId_pais(tablaPais.getValueAt(fila, 0).toString());
                if (JOptionPane.showConfirmDialog(this, "Desea eliminar registro?", "",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
                    if (funcionesPaises.isDelete(s)){
                        new rojerusan.RSNotifyFade("EXITO", "Se ha eliminado", 5, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                        funcionesPaises.setListar("");
                        funciones.funcionesAuditoria.auditoria(fecha, hora, evento, tabla, login.funcionesLogin.idFuncionario);
                        funciones.funcionesPaises.extraerIDMaxPAIS();
                    }
                }
        } else {
            new rojerusan.RSNotifyFade("ADVERTENCIA", "Seleccione un pais", 5, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.WARNING).setVisible(true);
        }
    }//GEN-LAST:event_botonEliminarPaisActionPerformed

    private void botonModificarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarPaisActionPerformed
            
        int selec3 = tablaPais.getSelectedRow();
        if (selec3 >-1) {
            int fila = tablaPais.getSelectedRow();
            Frame f = JOptionPane.getFrameForComponent(this);
            ModificarPais dialog = new ModificarPais (f, true);
            dialog.txtModificarPais.setText(tablaPais.getValueAt(fila, 1).toString());
            dialog.txtid.setText(tablaPais.getValueAt(fila, 0).toString());
            dialog.show();
        } else {
            new rojerusan.RSNotifyFade("ADVERTENCIA", "Seleccione un pais", 5, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.WARNING).setVisible(true);
        }
    }//GEN-LAST:event_botonModificarPaisActionPerformed

    private void txtBuscarPaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPaisKeyReleased
        librerias.Mayusculas.convertiraMayusculasEnJtextfield(txtBuscarPais);
        funcionesPaises.setListar(this.txtBuscarPais.getText());
    }//GEN-LAST:event_txtBuscarPaisKeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtBuscarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPaisActionPerformed

    private void txtAgregarPaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgregarPaisKeyReleased
        librerias.Mayusculas.convertiraMayusculasEnJtextfield(txtAgregarPais);
    }//GEN-LAST:event_txtAgregarPaisKeyReleased

    private void txtAgregarPaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgregarPaisKeyTyped
       if (txtAgregarPais.getText().length() >=50) {
            evt.consume();
        } if(librerias.Validaciones.Letras(evt.getKeyChar()) && librerias.Validaciones.Espacio(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAgregarPaisKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover botonAgregarPais;
    private rojerusan.RSButtonHover botonEliminarPais;
    private rojerusan.RSButtonHover botonModificarPais;
    private org.jdesktop.core.animation.timing.evaluators.EvaluatorShort evaluatorShort1;
    private javax.swing.JLabel idPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static rojerusan.RSTableMetro tablaPais;
    private rojerusan.RSMetroTextFullPlaceHolder txtAgregarPais;
    private rojerusan.RSMetroTextFullPlaceHolder txtBuscarPais;
    // End of variables declaration//GEN-END:variables
}
