/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JFrame;


/**
 *
 * @author SailorSakura
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        rsutilities.RSUtilities.setCentrarVentana(this);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        idCuentaPrincipal.setVisible(false);
        lblCuentaPrincipal.setVisible(false);
        lblSaldoPrincipal.setVisible(false);
        txtSaldoPrincipal.setVisible(false);
       // funciones.funcionesCaja.habilitarApertura();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblfecha = new rojeru_san.RSLabelFecha();
        lblhora = new rojeru_san.RSLabelHora();
        jPanel2 = new javax.swing.JPanel();
        botonMantenimiento = new rojerusan.RSButtonHover();
        botonClientes = new rojerusan.RSButtonHover();
        botonInventario = new rojerusan.RSButtonHover();
        botonOrdenCompra = new rojerusan.RSButtonHover();
        botonOrdenServicios = new rojerusan.RSButtonHover();
        botonCompra = new rojerusan.RSButtonHover();
        botonVentas = new rojerusan.RSButtonHover();
        botonCaja = new rojerusan.RSButtonHover();
        botonUsuarioPrincipal = new rojerusan.RSButtonHover();
        botonWeb = new rojerusan.RSButtonHover();
        botonCerrarSesion = new rojerusan.RSButtonHover();
        botonSalir = new rojerusan.RSButtonHover();
        idCuentaPrincipal = new javax.swing.JLabel();
        lblSaldoPrincipal = new javax.swing.JLabel();
        txtSaldoPrincipal = new javax.swing.JTextField();
        lblCuentaPrincipal = new javax.swing.JLabel();
        botonMaximinar = new rojerusan.RSButtonHover();
        botonMinimizar = new rojerusan.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/8BITS2.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Bienvenidos al sistema, ");

        lblfecha.setForeground(new java.awt.Color(240, 4, 7));
        lblfecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblfecha.setMaximumSize(new java.awt.Dimension(120, 120));
        lblfecha.setMinimumSize(new java.awt.Dimension(20, 20));

        lblhora.setForeground(new java.awt.Color(240, 4, 7));
        lblhora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblhora.setMaximumSize(new java.awt.Dimension(120, 120));
        lblhora.setMinimumSize(new java.awt.Dimension(20, 20));

        jPanel2.setBackground(new java.awt.Color(244, 213, 212));

        botonMantenimiento.setBackground(new java.awt.Color(11, 11, 11));
        botonMantenimiento.setText("MANTENIMIENTO");
        botonMantenimiento.setColorHover(new java.awt.Color(240, 4, 7));
        botonMantenimiento.setMaximumSize(new java.awt.Dimension(119, 25));
        botonMantenimiento.setMinimumSize(new java.awt.Dimension(119, 25));
        botonMantenimiento.setName("botonMantenimiento"); // NOI18N
        botonMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMantenimientoActionPerformed(evt);
            }
        });

        botonClientes.setBackground(new java.awt.Color(11, 11, 11));
        botonClientes.setText("CLIENTES");
        botonClientes.setColorHover(new java.awt.Color(240, 4, 7));
        botonClientes.setName("botonClientes"); // NOI18N
        botonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClientesActionPerformed(evt);
            }
        });

        botonInventario.setBackground(new java.awt.Color(11, 11, 11));
        botonInventario.setText("INVENTARIO");
        botonInventario.setColorHover(new java.awt.Color(240, 4, 7));
        botonInventario.setName("botonInventario"); // NOI18N
        botonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInventarioActionPerformed(evt);
            }
        });

        botonOrdenCompra.setBackground(new java.awt.Color(11, 11, 11));
        botonOrdenCompra.setText("ORDEN DE COMPRA");
        botonOrdenCompra.setColorHover(new java.awt.Color(240, 4, 7));
        botonOrdenCompra.setMaximumSize(new java.awt.Dimension(119, 25));
        botonOrdenCompra.setMinimumSize(new java.awt.Dimension(119, 25));
        botonOrdenCompra.setName("botonOrdenCompra"); // NOI18N
        botonOrdenCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenCompraActionPerformed(evt);
            }
        });

        botonOrdenServicios.setBackground(new java.awt.Color(11, 11, 11));
        botonOrdenServicios.setText("ORDEN DE SERVICIOS");
        botonOrdenServicios.setColorHover(new java.awt.Color(240, 4, 7));
        botonOrdenServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOrdenServiciosActionPerformed(evt);
            }
        });

        botonCompra.setBackground(new java.awt.Color(11, 11, 11));
        botonCompra.setText("LISTA DE COMPRAS");
        botonCompra.setColorHover(new java.awt.Color(240, 4, 7));
        botonCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCompraActionPerformed(evt);
            }
        });

        botonVentas.setBackground(new java.awt.Color(11, 11, 11));
        botonVentas.setText("VENTAS");
        botonVentas.setColorHover(new java.awt.Color(240, 4, 7));
        botonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentasActionPerformed(evt);
            }
        });

        botonCaja.setBackground(new java.awt.Color(11, 11, 11));
        botonCaja.setText("CAJA");
        botonCaja.setColorHover(new java.awt.Color(240, 4, 7));
        botonCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCajaActionPerformed(evt);
            }
        });

        botonUsuarioPrincipal.setBackground(new java.awt.Color(11, 11, 11));
        botonUsuarioPrincipal.setText("Modificar Contraseña");
        botonUsuarioPrincipal.setColorHover(new java.awt.Color(240, 4, 7));
        botonUsuarioPrincipal.setMaximumSize(new java.awt.Dimension(119, 25));
        botonUsuarioPrincipal.setMinimumSize(new java.awt.Dimension(119, 25));
        botonUsuarioPrincipal.setName("botonMantenimiento"); // NOI18N
        botonUsuarioPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuarioPrincipalActionPerformed(evt);
            }
        });

        botonWeb.setBackground(new java.awt.Color(11, 11, 11));
        botonWeb.setText("MENSAJES DE LA WEB");
        botonWeb.setColorHover(new java.awt.Color(240, 4, 7));
        botonWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonWebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonUsuarioPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonOrdenServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(botonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonOrdenServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(botonUsuarioPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        botonClientes.getAccessibleContext().setAccessibleDescription("");

        botonCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        botonCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar sesion.png"))); // NOI18N
        botonCerrarSesion.setText("Cerrar sesión");
        botonCerrarSesion.setColorHover(new java.awt.Color(240, 198, 196));
        botonCerrarSesion.setColorText(new java.awt.Color(0, 0, 0));
        botonCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(255, 255, 255));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-cerrar2.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setColorHover(new java.awt.Color(240, 198, 196));
        botonSalir.setColorText(new java.awt.Color(0, 0, 0));
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        idCuentaPrincipal.setText("IdC");

        lblSaldoPrincipal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSaldoPrincipal.setText("Saldo:");

        txtSaldoPrincipal.setEditable(false);
        txtSaldoPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lblCuentaPrincipal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCuentaPrincipal.setText("lblCuenta");

        botonMaximinar.setBackground(new java.awt.Color(255, 255, 255));
        botonMaximinar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/expandir.png"))); // NOI18N
        botonMaximinar.setText("Pantalla Completa");
        botonMaximinar.setColorHover(new java.awt.Color(240, 198, 196));
        botonMaximinar.setColorText(new java.awt.Color(0, 0, 0));
        botonMaximinar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        botonMaximinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMaximinarActionPerformed(evt);
            }
        });

        botonMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        botonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minimizar.png"))); // NOI18N
        botonMinimizar.setText("Minimizar Ventana");
        botonMinimizar.setColorHover(new java.awt.Color(240, 198, 196));
        botonMinimizar.setColorText(new java.awt.Color(0, 0, 0));
        botonMinimizar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        botonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMinimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSaldoPrincipal)
                                    .addComponent(idCuentaPrincipal))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCuentaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSaldoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(botonMaximinar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(idCuentaPrincipal)
                                .addGap(18, 18, 18)
                                .addComponent(lblSaldoPrincipal))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCuentaPrincipal)
                                .addGap(18, 18, 18)
                                .addComponent(txtSaldoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonMaximinar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOrdenCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenCompraActionPerformed
        if (txtSaldoPrincipal.getText().length()>0) {
            ListadoOrdenCompra p = new ListadoOrdenCompra();
            this.jDesktopPane1.add(p);
            p.setVisible(true);
            p.setUI(null);
            librerias.UtilitariosFrame.centrarInternalFrame(jDesktopPane1, p);
        } else {
            NotificacionApertura b = new NotificacionApertura(new JFrame(), true);
            b.show();
        }
        
    }//GEN-LAST:event_botonOrdenCompraActionPerformed

    private void botonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClientesActionPerformed
       // if (txtSaldoPrincipal.getText().length()>0) {
            Clientes p = new Clientes();
            this.jDesktopPane1.add(p);
            p.setVisible(true);
            p.setUI(null);
            librerias.UtilitariosFrame.centrarInternalFrame(jDesktopPane1, p);
      //  } else {
      //      NotificacionApertura b = new NotificacionApertura(new JFrame(), true);
      //      b.show();
      //  }
        
    }//GEN-LAST:event_botonClientesActionPerformed

    private void botonMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMantenimientoActionPerformed
        
     //   if (txtSaldoPrincipal.getText().length()>0) {
            Mantenimientos m = new Mantenimientos();
            this.jDesktopPane1.add(m);
            m.setVisible(true);
            m.setUI(null);
            librerias.UtilitariosFrame.centrarInternalFrame(jDesktopPane1, m);
     //   } else {
     //       NotificacionApertura b = new NotificacionApertura(new JFrame(), true);
     //       b.show();
     //   }
    }//GEN-LAST:event_botonMantenimientoActionPerformed

    private void botonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioActionPerformed
        
       // if (txtSaldoPrincipal.getText().length()>0) {
            Inventario p = new Inventario();
            this.jDesktopPane1.add(p);
            p.setVisible(true);
            p.setUI(null);
            librerias.UtilitariosFrame.centrarInternalFrame(jDesktopPane1, p);
       // } else {
       //     NotificacionApertura b = new NotificacionApertura(new JFrame(), true);
       //     b.show();
       // }
    }//GEN-LAST:event_botonInventarioActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        this.dispose();
        new login.Login().setVisible(true);
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCompraActionPerformed
        
        if (txtSaldoPrincipal.getText().length()>0) {
            ListadoCompras p = new ListadoCompras();
            this.jDesktopPane1.add(p);
            p.setVisible(true);
            p.setUI(null);
            librerias.UtilitariosFrame.centrarInternalFrame(jDesktopPane1, p);
        } else {
            NotificacionApertura b = new NotificacionApertura(new JFrame(), true);
            b.show();
        }
    }//GEN-LAST:event_botonCompraActionPerformed

    private void botonOrdenServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOrdenServiciosActionPerformed
        
        if (txtSaldoPrincipal.getText().length()>0) {
            ListadoOrdenServicios p = new ListadoOrdenServicios();
            this.jDesktopPane1.add(p);
            p.setVisible(true);
            p.setUI(null);
            librerias.UtilitariosFrame.centrarInternalFrame(jDesktopPane1, p);
        } else {
            NotificacionApertura b = new NotificacionApertura(new JFrame(), true);
            b.show();
        }
    }//GEN-LAST:event_botonOrdenServiciosActionPerformed

    private void botonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentasActionPerformed
        
        if (txtSaldoPrincipal.getText().length()>0) {
            OpcionesVentas b = new OpcionesVentas(new JFrame(), true);
            b.show();
        } else {
            NotificacionApertura b = new NotificacionApertura(new JFrame(), true);
            b.show();
        }
    }//GEN-LAST:event_botonVentasActionPerformed

    private void botonCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCajaActionPerformed
        Caja p = new Caja();
        this.jDesktopPane1.add(p);
        p.setVisible(true);
        p.setUI(null);
        librerias.UtilitariosFrame.centrarInternalFrame(jDesktopPane1, p);
    }//GEN-LAST:event_botonCajaActionPerformed

    private void botonUsuarioPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuarioPrincipalActionPerformed
        
        //if (txtSaldoPrincipal.getText().length()>0) {
            ModificarUsuarioPrincipal b = new ModificarUsuarioPrincipal(new JFrame(), true);
            ModificarUsuarioPrincipal.txtUserP.setText(login.funcionesLogin.UserPrincipal);
         //   ModificarUsuarioPrincipal.txtContraP.setText(login.funcionesLogin.PassPrincipal);
     //   ModificarUsuarioPrincipal.lblTipoP.setText(login.funcionesLogin.TipoPrincipal);
            ModificarUsuarioPrincipal.idUserPrincipal.setText(login.funcionesLogin.idUserPrincipal);
        b.show();
      //  } else {
       //     NotificacionApertura b = new NotificacionApertura(new JFrame(), true);
       //     b.show();
       // }
    }//GEN-LAST:event_botonUsuarioPrincipalActionPerformed

    private void botonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_botonMinimizarActionPerformed

    private void botonMaximinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMaximinarActionPerformed
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_botonMaximinarActionPerformed

    private void botonWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonWebActionPerformed
       // if (txtSaldoPrincipal.getText().length()>0) {
            MensajesWeb p = new MensajesWeb();
            this.jDesktopPane1.add(p);
            p.setVisible(true);
            p.setUI(null);
            librerias.UtilitariosFrame.centrarInternalFrame(jDesktopPane1, p);
      //  } else {
      //      NotificacionApertura b = new NotificacionApertura(new JFrame(), true);
      //      b.show();
      //  }
    }//GEN-LAST:event_botonWebActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static rojerusan.RSButtonHover botonCaja;
    private rojerusan.RSButtonHover botonCerrarSesion;
    public static rojerusan.RSButtonHover botonClientes;
    public static rojerusan.RSButtonHover botonCompra;
    public static rojerusan.RSButtonHover botonInventario;
    public static rojerusan.RSButtonHover botonMantenimiento;
    private rojerusan.RSButtonHover botonMaximinar;
    private rojerusan.RSButtonHover botonMinimizar;
    public static rojerusan.RSButtonHover botonOrdenCompra;
    public static rojerusan.RSButtonHover botonOrdenServicios;
    private rojerusan.RSButtonHover botonSalir;
    public static rojerusan.RSButtonHover botonUsuarioPrincipal;
    public static rojerusan.RSButtonHover botonVentas;
    private rojerusan.RSButtonHover botonWeb;
    public static javax.swing.JLabel idCuentaPrincipal;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblCuentaPrincipal;
    private javax.swing.JLabel lblSaldoPrincipal;
    public static rojeru_san.RSLabelFecha lblfecha;
    public static rojeru_san.RSLabelHora lblhora;
    public static javax.swing.JTextField txtSaldoPrincipal;
    // End of variables declaration//GEN-END:variables
}
