/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import rojerusan.RSNotifyFade;

/**
 *
 * @author SailorSakura
 */
public class RegistrarOrdenServicios extends javax.swing.JInternalFrame {
    private static   Conexion conexion = new Conexion();
    private static   Connection conexionActual = conexion.conectar();
    private static PreparedStatement ps= null;
    /**
     * Creates new form RegistrarOrdenServicios
     */
    public RegistrarOrdenServicios() {
        initComponents();
        funciones.funcionesOrdenServicios.cargarComboFuncionario();
        idOrdenSer.setText(funciones.funcionesOrdenServicios.extraerIDMaxOrdenSer());
        idPro.setText(funciones.funcionesOrdenServicios.extraerIDMaxDetProd());
        idSer.setText(funciones.funcionesOrdenServicios.extraerIDMaxDetSer());
        dateSeleccion.setText(FechaActual());
        IdCliente.setVisible(false);
        idOrdenSer.setVisible(false);
        idPro.setVisible(false);
        idSer.setVisible(false);
        
        rSPopuMenu1.add(EliminarOS);
        rSPopuMenu2.add(EliminarServ);
    }
public static void Calcular(){
    int precioSer = 0, sumaSer = 0, precioProd = 0, cant = 0 , suma = 0, multiplo = 0, totalGen =0;
    
    for (int i = 0; i < tablaOrdenServicios.getRowCount(); i++) {
        precioSer = Integer.parseInt(tablaOrdenServicios.getValueAt(i,2).toString());
        sumaSer += precioSer;
    }
    for (int i = 0; i < tablaOrdenProductos.getRowCount(); i++) {
        precioProd = Integer.parseInt(tablaOrdenProductos.getValueAt(i,2).toString());
        cant = Integer.parseInt(tablaOrdenProductos.getValueAt(i,3).toString());
        multiplo = precioProd * cant;
        suma += multiplo;
    }
    totalGen = suma + sumaSer;
    txtTotal.setText(String.valueOf(totalGen));
}

public static String FechaActual(){
    Date fecha = new Date();
    SimpleDateFormat formatofecha= new SimpleDateFormat("dd/MM/yyyy");
    return formatofecha.format(fecha);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPopuMenu1 = new rojerusan.RSPopuMenu();
        EliminarOS = new javax.swing.JPanel();
        botonEliminarOS = new rojerusan.RSButtonHover();
        rSPopuMenu2 = new rojerusan.RSPopuMenu();
        EliminarServ = new javax.swing.JPanel();
        botonEliminarServ = new rojerusan.RSButtonHover();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonTipoServicios = new rojerusan.RSButtonHover();
        idOrdenSer = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDescripcion = new rojerusan.RSMetroTextFullPlaceHolder();
        jLabel4 = new javax.swing.JLabel();
        botonRegistrarOrden = new rojerusan.RSButtonHover();
        jLabel7 = new javax.swing.JLabel();
        comboTecnico = new rojerusan.RSComboMetro();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOrdenProductos = new rojerusan.RSTableMetro();
        botonClientes = new rojerusan.RSButtonHover();
        IdCliente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaOrdenServicios = new rojerusan.RSTableMetro();
        lblCliente = new javax.swing.JLabel();
        botonInventario = new rojerusan.RSButtonHover();
        botonCalcular = new rojerusan.RSButtonHover();
        idSer = new javax.swing.JLabel();
        idPro = new javax.swing.JLabel();
        dateSeleccion = new javax.swing.JTextField();

        EliminarOS.setBackground(new java.awt.Color(255, 255, 255));
        EliminarOS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonEliminarOS.setBackground(new java.awt.Color(11, 11, 11));
        botonEliminarOS.setText("Eliminar");
        botonEliminarOS.setColorHover(new java.awt.Color(240, 4, 7));
        botonEliminarOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EliminarOSLayout = new javax.swing.GroupLayout(EliminarOS);
        EliminarOS.setLayout(EliminarOSLayout);
        EliminarOSLayout.setHorizontalGroup(
            EliminarOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarOSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminarOS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EliminarOSLayout.setVerticalGroup(
            EliminarOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarOSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminarOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EliminarServ.setBackground(new java.awt.Color(255, 255, 255));
        EliminarServ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonEliminarServ.setBackground(new java.awt.Color(11, 11, 11));
        botonEliminarServ.setText("Eliminar");
        botonEliminarServ.setColorHover(new java.awt.Color(240, 4, 7));
        botonEliminarServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarServActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EliminarServLayout = new javax.swing.GroupLayout(EliminarServ);
        EliminarServ.setLayout(EliminarServLayout);
        EliminarServLayout.setHorizontalGroup(
            EliminarServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarServLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminarServ, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EliminarServLayout.setVerticalGroup(
            EliminarServLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarServLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminarServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-cerrar2.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("ORDEN DE SERVICIOS");

        botonTipoServicios.setBackground(new java.awt.Color(11, 11, 11));
        botonTipoServicios.setText("Seleccione los Servicios");
        botonTipoServicios.setColorHover(new java.awt.Color(240, 4, 7));
        botonTipoServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTipoServiciosActionPerformed(evt);
            }
        });

        idOrdenSer.setText("ID");

        jLabel6.setText("Observaciones:");

        txtDescripcion.setForeground(new java.awt.Color(11, 11, 11));
        txtDescripcion.setBorderColor(new java.awt.Color(11, 11, 11));
        txtDescripcion.setBotonColor(new java.awt.Color(240, 4, 7));
        txtDescripcion.setPhColor(new java.awt.Color(0, 0, 0));
        txtDescripcion.setPlaceholder("");
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyReleased(evt);
            }
        });

        jLabel4.setText("Fecha:");

        botonRegistrarOrden.setBackground(new java.awt.Color(11, 11, 11));
        botonRegistrarOrden.setText("Registrar");
        botonRegistrarOrden.setColorHover(new java.awt.Color(240, 4, 7));
        botonRegistrarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarOrdenActionPerformed(evt);
            }
        });

        jLabel7.setText("Tecnico:");

        comboTecnico.setColorArrow(new java.awt.Color(240, 4, 7));
        comboTecnico.setColorBorde(new java.awt.Color(11, 11, 11));
        comboTecnico.setColorFondo(new java.awt.Color(242, 134, 130));
        comboTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTecnicoActionPerformed(evt);
            }
        });

        lblTotal.setText("Total");

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTotal.setSelectionColor(new java.awt.Color(240, 4, 7));

        tablaOrdenProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Precio", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaOrdenProductos.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaOrdenProductos.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaOrdenProductos.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaOrdenProductos.setComponentPopupMenu(rSPopuMenu1);
        tablaOrdenProductos.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane1.setViewportView(tablaOrdenProductos);
        if (tablaOrdenProductos.getColumnModel().getColumnCount() > 0) {
            tablaOrdenProductos.getColumnModel().getColumn(0).setMinWidth(0);
            tablaOrdenProductos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        botonClientes.setBackground(new java.awt.Color(11, 11, 11));
        botonClientes.setText("Seleccione Cliente");
        botonClientes.setColorHover(new java.awt.Color(240, 4, 7));
        botonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClientesActionPerformed(evt);
            }
        });

        IdCliente.setText("IDCliente");

        tablaOrdenServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Servicio", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaOrdenServicios.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaOrdenServicios.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaOrdenServicios.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaOrdenServicios.setComponentPopupMenu(rSPopuMenu2);
        tablaOrdenServicios.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane2.setViewportView(tablaOrdenServicios);
        if (tablaOrdenServicios.getColumnModel().getColumnCount() > 0) {
            tablaOrdenServicios.getColumnModel().getColumn(0).setMinWidth(0);
            tablaOrdenServicios.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        lblCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCliente.setText("SIN NOMBRE");

        botonInventario.setBackground(new java.awt.Color(11, 11, 11));
        botonInventario.setText("Seleccione Productos");
        botonInventario.setColorHover(new java.awt.Color(240, 4, 7));
        botonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInventarioActionPerformed(evt);
            }
        });

        botonCalcular.setBackground(new java.awt.Color(11, 11, 11));
        botonCalcular.setText("Calcular");
        botonCalcular.setColorHover(new java.awt.Color(240, 4, 7));
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });

        idSer.setText("IDSer");

        idPro.setText("IDPr");

        dateSeleccion.setEditable(false);
        dateSeleccion.setBackground(new java.awt.Color(255, 255, 255));
        dateSeleccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dateSeleccion.setSelectionColor(new java.awt.Color(240, 4, 7));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonTipoServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(IdCliente)
                                .addGap(18, 18, 18)
                                .addComponent(idSer)
                                .addGap(18, 18, 18)
                                .addComponent(idPro)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblTotal)
                        .addGap(36, 36, 36)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(idOrdenSer)
                        .addGap(27, 27, 27)
                        .addComponent(botonRegistrarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(279, 279, 279)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCliente)
                        .addGap(18, 18, 18)
                        .addComponent(botonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonTipoServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(comboTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(dateSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(botonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTotal))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonRegistrarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idOrdenSer)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdCliente)
                            .addComponent(idSer)
                            .addComponent(idPro))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void botonTipoServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTipoServiciosActionPerformed
        VerOrdenServicios f = new VerOrdenServicios(new JFrame(), true);
        f.setVisible(true);
    }//GEN-LAST:event_botonTipoServiciosActionPerformed

    private void botonRegistrarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarOrdenActionPerformed
        if (txtDescripcion.getText().length() == 0 || txtTotal.getText().length() == 0 || comboTecnico.getSelectedIndex() < 0 || lblCliente.getText().length() == 0 || tablaOrdenServicios.getSelectedRowCount() < -1) {
                new rojerusan.RSNotifyFade("ERROR", "Ingrese todos los campos", 5, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.ERROR).setVisible(true);
            } else {
                funciones.funcionesOrdenServicios.guardarOrdenServicio();
                new rojerusan.RSNotifyFade("EXITO", "Se ha registrado la orden", 5, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                    try {
                        JasperReport jr = (JasperReport) JRLoader.loadObject(getClass().getResource("/reportes/OrdenServicio.jasper"));
            
                           Map parametro = new HashMap();
                        parametro.put("IDOrden", idOrdenSer.getText()); 
                        parametro.put("IMAGEN", getClass().getResourceAsStream("/imagenes/FacturaProducto.png"));
                        JasperPrint jp = JasperFillManager.fillReport(jr, parametro, conexionActual);
                        JasperViewer jv = new JasperViewer(jp, false);
                        jv.setVisible(true);
                        jv.setTitle("Reporte único de Servicio");
                    } catch (JRException ex) {
                        System.err.println("Error: "+ex.getMessage());
                    }
            this.dispose();
            }
        
    }//GEN-LAST:event_botonRegistrarOrdenActionPerformed

    private void comboTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTecnicoActionPerformed

    private void botonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClientesActionPerformed
        VerClientesOrdenSer f = new VerClientesOrdenSer(new JFrame(), true);
        f.setVisible(true);
    }//GEN-LAST:event_botonClientesActionPerformed

    private void botonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioActionPerformed
        VerOrdenProductos f = new VerOrdenProductos(new JFrame(), true);
        f.setVisible(true);
        
    }//GEN-LAST:event_botonInventarioActionPerformed

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        Calcular();
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void botonEliminarOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarOSActionPerformed
        int fila = tablaOrdenProductos.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tablaOrdenProductos.getModel();
        modelo.removeRow(fila);
        rSPopuMenu1.setVisible(false);
    }//GEN-LAST:event_botonEliminarOSActionPerformed

    private void botonEliminarServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarServActionPerformed
        int fila = tablaOrdenServicios.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tablaOrdenServicios.getModel();
        modelo.removeRow(fila);
        rSPopuMenu2.setVisible(false);
    }//GEN-LAST:event_botonEliminarServActionPerformed

    private void txtDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyReleased
        librerias.Mayusculas.convertiraMayusculasEnJtextfield(txtDescripcion);
    }//GEN-LAST:event_txtDescripcionKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EliminarOS;
    private javax.swing.JPanel EliminarServ;
    public static javax.swing.JLabel IdCliente;
    private rojerusan.RSButtonHover botonCalcular;
    private rojerusan.RSButtonHover botonClientes;
    private rojerusan.RSButtonHover botonEliminarOS;
    private rojerusan.RSButtonHover botonEliminarServ;
    private rojerusan.RSButtonHover botonInventario;
    private rojerusan.RSButtonHover botonRegistrarOrden;
    private rojerusan.RSButtonHover botonTipoServicios;
    public static rojerusan.RSComboMetro comboTecnico;
    public static javax.swing.JTextField dateSeleccion;
    public static javax.swing.JLabel idOrdenSer;
    public static javax.swing.JLabel idPro;
    public static javax.swing.JLabel idSer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblTotal;
    private rojerusan.RSPopuMenu rSPopuMenu1;
    private rojerusan.RSPopuMenu rSPopuMenu2;
    public static rojerusan.RSTableMetro tablaOrdenProductos;
    public static rojerusan.RSTableMetro tablaOrdenServicios;
    public static rojerusan.RSMetroTextFullPlaceHolder txtDescripcion;
    public static javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
