/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import rojerusan.RSNotifyAnimated;
import rojerusan.RSNotifyFade;

/**
 *
 * @author SailorSakura
 */
public class RegistrarVentaInventario extends javax.swing.JInternalFrame {
    private static   Conexion conexion = new Conexion();
    private static   Connection conexionActual = conexion.conectar();
    private static PreparedStatement ps= null;
    /**
     * Creates new form RegistrarVentaInventario
     */
    public RegistrarVentaInventario() {
        initComponents();
        funciones.funcionesVentas.numeros();
        idVentasInven.setText(funciones.funcionesVentas.extraerIDMaxVentasInven());
        idDetV.setText(funciones.funcionesVentas.extraerIDMaxDetVentasInven());
       //IdCliente.setVisible(false);
       dateSeleccion.setText(FechaActual());
       rSPopuMenu1.add(EliminarVen);
       IdCliente.setVisible(false);
       idDetV.setVisible(false);
       idVentasInven.setVisible(false);
    }
    
    public static String FechaActual(){
    Date fecha = new Date();
    SimpleDateFormat formatofecha= new SimpleDateFormat("dd/MM/yyyy");
    return formatofecha.format(fecha);
}
    
    
public static void Calcular(){
    int precioInven = 0, sumaInven = 0, cant = 0 , suma = 0, multiplo = 0, totalGen =0;
    int subTotal = 0, imp = 0, sub = 0;
    
    
    for (int i = 0; i < tablaVentaInven.getRowCount(); i++) {
        precioInven = Integer.parseInt(tablaVentaInven.getValueAt(i,2).toString());
        cant = Integer.parseInt(tablaVentaInven.getValueAt(i,3).toString());
        imp = Integer.parseInt(tablaVentaInven.getValueAt(i, 4).toString());
        multiplo = precioInven * cant;
        suma += multiplo;
        
    }
    
    totalGen = suma + sumaInven;
    txtTotalGen.setText(String.valueOf(totalGen));
    
    sub = (totalGen * imp)/100; 
    subTotal = totalGen-sub;
     txtSubTotal.setText(String.valueOf(subTotal));
     txtTotalImpuesto.setText(String.valueOf(sub));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPopuMenu1 = new rojerusan.RSPopuMenu();
        EliminarVen = new javax.swing.JPanel();
        botonEliminarVen = new rojerusan.RSButtonHover();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonClientes = new rojerusan.RSButtonHover();
        IdCliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonRegistrarOrden = new rojerusan.RSButtonHover();
        lblCliente = new javax.swing.JLabel();
        botonInventario = new rojerusan.RSButtonHover();
        botonCalcular = new rojerusan.RSButtonHover();
        lblTotal = new javax.swing.JLabel();
        txtTotalGen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentaInven = new rojerusan.RSTableMetro();
        txtCodigoInven = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        lblTotal2 = new javax.swing.JLabel();
        txtTotalImpuesto = new javax.swing.JTextField();
        idVentasInven = new javax.swing.JLabel();
        idDetV = new javax.swing.JLabel();
        dateSeleccion = new javax.swing.JTextField();

        EliminarVen.setBackground(new java.awt.Color(255, 255, 255));
        EliminarVen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonEliminarVen.setBackground(new java.awt.Color(11, 11, 11));
        botonEliminarVen.setText("Eliminar");
        botonEliminarVen.setColorHover(new java.awt.Color(240, 4, 7));
        botonEliminarVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarVenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EliminarVenLayout = new javax.swing.GroupLayout(EliminarVen);
        EliminarVen.setLayout(EliminarVenLayout);
        EliminarVenLayout.setHorizontalGroup(
            EliminarVenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarVenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminarVen, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EliminarVenLayout.setVerticalGroup(
            EliminarVenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarVenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminarVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-cerrar2.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("REGISTRO DE VENTAS");

        botonClientes.setBackground(new java.awt.Color(11, 11, 11));
        botonClientes.setText("Seleccione Cliente");
        botonClientes.setColorHover(new java.awt.Color(240, 4, 7));
        botonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClientesActionPerformed(evt);
            }
        });

        IdCliente.setText("IDCliente");

        jLabel4.setText("Fecha:");

        botonRegistrarOrden.setBackground(new java.awt.Color(11, 11, 11));
        botonRegistrarOrden.setText("Registrar");
        botonRegistrarOrden.setColorHover(new java.awt.Color(240, 4, 7));
        botonRegistrarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarOrdenActionPerformed(evt);
            }
        });

        lblCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCliente.setText("SIN NOMBRE");

        botonInventario.setBackground(new java.awt.Color(11, 11, 11));
        botonInventario.setText("Seleccione productos");
        botonInventario.setColorHover(new java.awt.Color(240, 4, 7));
        botonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInventarioActionPerformed(evt);
            }
        });

        botonCalcular.setBackground(new java.awt.Color(11, 11, 11));
        botonCalcular.setText("Calcular");
        botonCalcular.setColorHover(new java.awt.Color(240, 4, 7));
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });

        lblTotal.setText("Total");

        txtTotalGen.setEditable(false);
        txtTotalGen.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalGen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalGen.setForeground(new java.awt.Color(11, 11, 11));
        txtTotalGen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalGen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTotalGen.setSelectionColor(new java.awt.Color(240, 4, 7));

        tablaVentaInven.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Precio", "Cantidad", "Impuestos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentaInven.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaVentaInven.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaVentaInven.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaVentaInven.setComponentPopupMenu(rSPopuMenu1);
        tablaVentaInven.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane1.setViewportView(tablaVentaInven);
        if (tablaVentaInven.getColumnModel().getColumnCount() > 0) {
            tablaVentaInven.getColumnModel().getColumn(0).setMinWidth(0);
            tablaVentaInven.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        txtCodigoInven.setEditable(false);
        txtCodigoInven.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoInven.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCodigoInven.setForeground(new java.awt.Color(11, 11, 11));
        txtCodigoInven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCodigoInven.setSelectionColor(new java.awt.Color(240, 4, 7));
        txtCodigoInven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoInvenActionPerformed(evt);
            }
        });

        jLabel3.setText("Timbrado:");

        lblTotal1.setText("Sub-Total:");

        txtSubTotal.setEditable(false);
        txtSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtSubTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubTotal.setForeground(new java.awt.Color(11, 11, 11));
        txtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubTotal.setSelectionColor(new java.awt.Color(240, 4, 7));

        lblTotal2.setText("Total Impuestos:");

        txtTotalImpuesto.setEditable(false);
        txtTotalImpuesto.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalImpuesto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalImpuesto.setForeground(new java.awt.Color(11, 11, 11));
        txtTotalImpuesto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalImpuesto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTotalImpuesto.setSelectionColor(new java.awt.Color(240, 4, 7));

        idVentasInven.setText("ID");

        idDetV.setText("IDDV");

        dateSeleccion.setEditable(false);
        dateSeleccion.setBackground(new java.awt.Color(255, 255, 255));
        dateSeleccion.setForeground(new java.awt.Color(11, 11, 11));
        dateSeleccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dateSeleccion.setSelectionColor(new java.awt.Color(240, 4, 7));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoInven, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdCliente, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(dateSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(botonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTotal1)
                                .addGap(18, 18, 18)
                                .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(589, 589, 589))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(286, 286, 286)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(idDetV)
                                        .addGap(67, 67, 67)
                                        .addComponent(idVentasInven))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTotal2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTotalImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTotal)
                                        .addGap(36, 36, 36)
                                        .addComponent(txtTotalGen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonRegistrarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigoInven, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(dateSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(botonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal1)
                    .addComponent(txtTotalGen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotalImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal2)
                    .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistrarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idVentasInven)
                    .addComponent(IdCliente)
                    .addComponent(idDetV))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void botonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClientesActionPerformed
        VerClientesVentasInven f = new VerClientesVentasInven(new JFrame(), true);
        f.setVisible(true);
    }//GEN-LAST:event_botonClientesActionPerformed

    private void botonRegistrarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarOrdenActionPerformed
        int tabla = tablaVentaInven.getSelectedRowCount();
        if (tabla > -1){
        if (txtTotalGen.getText().length()==0 || lblCliente.getText().length()==0) {
            new rojerusan.RSNotifyFade("ADVERTENCIA", "Registre todos los campos", 5, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.WARNING).setVisible(true);
        } else {
        funciones.funcionesVentas.guardarVentasInven();
        
        try {
            JasperReport jr = (JasperReport) JRLoader.loadObject(getClass().getResource("/reportes/FacturaProducto.jasper"));
            System.out.println("Id Alumno: ");
            Map parametro = new HashMap();
                parametro.put("IDFactura", idVentasInven.getText()); 
                parametro.put("IMAGEN", getClass().getResourceAsStream("/imagenes/FacturaProducto.png"));
            JasperPrint jp = JasperFillManager.fillReport(jr, parametro, conexionActual);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            jv.setTitle("Factura Producto");
        } catch (JRException ex) {
             System.err.println("Error: "+ex.getMessage());
    }
        this.dispose();
        } 
            

        }
    }//GEN-LAST:event_botonRegistrarOrdenActionPerformed

    private void botonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioActionPerformed
        VerVentasInven f = new VerVentasInven(new JFrame(), true);
        f.setVisible(true);
    }//GEN-LAST:event_botonInventarioActionPerformed

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        Calcular();
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void txtCodigoInvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoInvenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoInvenActionPerformed

    private void botonEliminarVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarVenActionPerformed
        int fila = tablaVentaInven.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tablaVentaInven.getModel();
        modelo.removeRow(fila);
        rSPopuMenu1.setVisible(false);
    }//GEN-LAST:event_botonEliminarVenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EliminarVen;
    public static javax.swing.JLabel IdCliente;
    public static rojerusan.RSButtonHover botonCalcular;
    private rojerusan.RSButtonHover botonClientes;
    private rojerusan.RSButtonHover botonEliminarVen;
    private rojerusan.RSButtonHover botonInventario;
    private rojerusan.RSButtonHover botonRegistrarOrden;
    public static javax.swing.JTextField dateSeleccion;
    public static javax.swing.JLabel idDetV;
    public static javax.swing.JLabel idVentasInven;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblTotal2;
    private rojerusan.RSPopuMenu rSPopuMenu1;
    public static rojerusan.RSTableMetro tablaVentaInven;
    public static javax.swing.JTextField txtCodigoInven;
    public static javax.swing.JTextField txtSubTotal;
    public static javax.swing.JTextField txtTotalGen;
    public static javax.swing.JTextField txtTotalImpuesto;
    // End of variables declaration//GEN-END:variables
}
