/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import rojerusan.RSNotifyAnimated;
import rojerusan.RSNotifyFade;

/**
 *
 * @author SailorSakura
 */
public class RegistrarVentaServicio extends javax.swing.JInternalFrame {
    private static   Conexion conexion = new Conexion();
    private static   Connection conexionActual = conexion.conectar();
    private static PreparedStatement ps= null;
    /**
     * Creates new form Ventas
     */
    public RegistrarVentaServicio() {
        initComponents();
        funciones.funcionesVentas.numerosServicios();
        idVentaSer.setText(funciones.funcionesVentas.extraerIDMaxVentasInven());
        idDetVentaSer.setText(funciones.funcionesVentas.extraerIDMaxDetVentasInven());
        dateSeleccion.setText(FechaActual());
        IdCliente.setVisible(false);
        idDetVentaSer.setVisible(false);
        idOrdenSer.setVisible(false);
        idVentaSer.setVisible(false);
        
        rSPopuMenu1.add(EliminarServicio);
        rSPopuMenu2.add(EliminarProduc);
    }
public static String FechaActual(){
    Date fecha = new Date();
    SimpleDateFormat formatofecha= new SimpleDateFormat("dd/MM/yyyy");
    return formatofecha.format(fecha);
}
    
    
public static void Calcular(){
    int precioSer = 0, sumaSer = 0, precioProd = 0, cant = 0 , suma = 0, multiplo = 0, totalGen =0;
    int subTotal = 0, imp = 0, sub = 0;
    for (int i = 0; i < tablaVentaServicios.getRowCount(); i++) {
        precioSer = Integer.parseInt(tablaVentaServicios.getValueAt(i,2).toString());
        sumaSer += precioSer;
    }
    for (int i = 0; i < tablaVentaProductos.getRowCount(); i++) {
        precioProd = Integer.parseInt(tablaVentaProductos.getValueAt(i,2).toString());
        cant = Integer.parseInt(tablaVentaProductos.getValueAt(i,3).toString());
        imp = Integer.parseInt(tablaVentaProductos.getValueAt(i, 4).toString());
        multiplo = precioProd * cant;
        suma += multiplo;
        imp += imp;
    }
    totalGen = suma + sumaSer;
    txtTotalGen.setText(String.valueOf(totalGen));   
    sub = (totalGen * imp)/100; 
    subTotal = totalGen-sub;
     txtSubTotal.setText(String.valueOf(subTotal));
     txtTotalImpuesto.setText(String.valueOf(sub));
}



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPopuMenu1 = new rojerusan.RSPopuMenu();
        EliminarServicio = new javax.swing.JPanel();
        botonEliminarServicio = new rojerusan.RSButtonHover();
        rSPopuMenu2 = new rojerusan.RSPopuMenu();
        EliminarProduc = new javax.swing.JPanel();
        botonEliminarProduc = new rojerusan.RSButtonHover();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonClientes = new rojerusan.RSButtonHover();
        IdCliente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVentaServicios = new rojerusan.RSTableMetro();
        jLabel4 = new javax.swing.JLabel();
        botonRegistrarVentaSer = new rojerusan.RSButtonHover();
        lblCliente = new javax.swing.JLabel();
        botonInventario = new rojerusan.RSButtonHover();
        botonCalcular = new rojerusan.RSButtonHover();
        lblTotal = new javax.swing.JLabel();
        txtTotalGen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentaProductos = new rojerusan.RSTableMetro();
        idOrdenSer = new javax.swing.JLabel();
        txtCodigoSer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        lblTotal2 = new javax.swing.JLabel();
        txtTotalImpuesto = new javax.swing.JTextField();
        idVentaSer = new javax.swing.JLabel();
        idDetVentaSer = new javax.swing.JLabel();
        dateSeleccion = new javax.swing.JTextField();

        EliminarServicio.setBackground(new java.awt.Color(255, 255, 255));
        EliminarServicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonEliminarServicio.setBackground(new java.awt.Color(11, 11, 11));
        botonEliminarServicio.setText("Eliminar");
        botonEliminarServicio.setColorHover(new java.awt.Color(240, 4, 7));
        botonEliminarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EliminarServicioLayout = new javax.swing.GroupLayout(EliminarServicio);
        EliminarServicio.setLayout(EliminarServicioLayout);
        EliminarServicioLayout.setHorizontalGroup(
            EliminarServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarServicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EliminarServicioLayout.setVerticalGroup(
            EliminarServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarServicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EliminarProduc.setBackground(new java.awt.Color(255, 255, 255));
        EliminarProduc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonEliminarProduc.setBackground(new java.awt.Color(11, 11, 11));
        botonEliminarProduc.setText("Eliminar");
        botonEliminarProduc.setColorHover(new java.awt.Color(240, 4, 7));
        botonEliminarProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarProducActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EliminarProducLayout = new javax.swing.GroupLayout(EliminarProduc);
        EliminarProduc.setLayout(EliminarProducLayout);
        EliminarProducLayout.setHorizontalGroup(
            EliminarProducLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarProducLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminarProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EliminarProducLayout.setVerticalGroup(
            EliminarProducLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarProducLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEliminarProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-cerrar2.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(876, 21, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("REGISTRO DE VENTAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 58, -1, -1));

        botonClientes.setBackground(new java.awt.Color(11, 11, 11));
        botonClientes.setText("Seleccione Cliente");
        botonClientes.setColorHover(new java.awt.Color(240, 4, 7));
        botonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClientesActionPerformed(evt);
            }
        });
        jPanel1.add(botonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 172, -1, -1));

        IdCliente.setText("IDCliente");
        jPanel1.add(IdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 440, -1, -1));

        tablaVentaServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Servicio", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentaServicios.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaVentaServicios.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaVentaServicios.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaVentaServicios.setComponentPopupMenu(rSPopuMenu1);
        tablaVentaServicios.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane2.setViewportView(tablaVentaServicios);
        if (tablaVentaServicios.getColumnModel().getColumnCount() > 0) {
            tablaVentaServicios.getColumnModel().getColumn(0).setMinWidth(0);
            tablaVentaServicios.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 172, 584, 146));

        jLabel4.setText("Fecha:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 305, -1, -1));

        botonRegistrarVentaSer.setBackground(new java.awt.Color(11, 11, 11));
        botonRegistrarVentaSer.setText("Registrar");
        botonRegistrarVentaSer.setColorHover(new java.awt.Color(240, 4, 7));
        botonRegistrarVentaSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarVentaSerActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegistrarVentaSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 578, -1, -1));

        lblCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCliente.setText("SIN NOMBRE");
        jPanel1.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 118, 272, -1));

        botonInventario.setBackground(new java.awt.Color(11, 11, 11));
        botonInventario.setText("Productos extras");
        botonInventario.setColorHover(new java.awt.Color(240, 4, 7));
        botonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInventarioActionPerformed(evt);
            }
        });
        jPanel1.add(botonInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        botonCalcular.setBackground(new java.awt.Color(11, 11, 11));
        botonCalcular.setText("Calcular");
        botonCalcular.setColorHover(new java.awt.Color(240, 4, 7));
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 354, -1, -1));

        lblTotal.setText("Total:");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, -1, -1));

        txtTotalGen.setEditable(false);
        txtTotalGen.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalGen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalGen.setForeground(new java.awt.Color(11, 11, 11));
        txtTotalGen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalGen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTotalGen.setSelectionColor(new java.awt.Color(240, 4, 7));
        jPanel1.add(txtTotalGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 506, 180, 40));

        tablaVentaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Precio", "Cantidad", "Impuestos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentaProductos.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaVentaProductos.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaVentaProductos.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaVentaProductos.setComponentPopupMenu(rSPopuMenu2);
        tablaVentaProductos.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane1.setViewportView(tablaVentaProductos);
        if (tablaVentaProductos.getColumnModel().getColumnCount() > 0) {
            tablaVentaProductos.getColumnModel().getColumn(0).setMinWidth(0);
            tablaVentaProductos.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 336, 584, 141));

        idOrdenSer.setText("IDOS");
        jPanel1.add(idOrdenSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 440, -1, -1));

        txtCodigoSer.setEditable(false);
        txtCodigoSer.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoSer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCodigoSer.setForeground(new java.awt.Color(11, 11, 11));
        txtCodigoSer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCodigoSer.setSelectionColor(new java.awt.Color(240, 4, 7));
        jPanel1.add(txtCodigoSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 105, 200, 40));

        jLabel3.setText("Timbrado:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 121, -1, -1));

        lblTotal1.setText("Sub-Total:");
        jPanel1.add(lblTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 520, -1, -1));

        txtSubTotal.setEditable(false);
        txtSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtSubTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSubTotal.setForeground(new java.awt.Color(11, 11, 11));
        txtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubTotal.setSelectionColor(new java.awt.Color(240, 4, 7));
        jPanel1.add(txtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 506, 180, 40));

        lblTotal2.setText("Total Impuestos:");
        jPanel1.add(lblTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 520, -1, -1));

        txtTotalImpuesto.setEditable(false);
        txtTotalImpuesto.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalImpuesto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalImpuesto.setForeground(new java.awt.Color(11, 11, 11));
        txtTotalImpuesto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalImpuesto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTotalImpuesto.setSelectionColor(new java.awt.Color(240, 4, 7));
        jPanel1.add(txtTotalImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 506, 180, 40));

        idVentaSer.setText("ID");
        jPanel1.add(idVentaSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 593, -1, -1));

        idDetVentaSer.setText("IDDVS");
        jPanel1.add(idDetVentaSer, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 593, -1, -1));

        dateSeleccion.setEditable(false);
        dateSeleccion.setBackground(new java.awt.Color(255, 255, 255));
        dateSeleccion.setForeground(new java.awt.Color(11, 11, 11));
        dateSeleccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dateSeleccion.setSelectionColor(new java.awt.Color(240, 4, 7));
        jPanel1.add(dateSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 292, 157, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void botonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClientesActionPerformed
        VerClientesVentasSer f = new VerClientesVentasSer(new JFrame(), true);
        f.setVisible(true);
    }//GEN-LAST:event_botonClientesActionPerformed

    private void botonRegistrarVentaSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarVentaSerActionPerformed
        
        int tabla = tablaVentaServicios.getSelectedRowCount();
        if (tabla > -1){
            if (txtTotalGen.getText().length()==0 || lblCliente.getText().length()==0) {
            new rojerusan.RSNotifyFade("ADVERTENCIA", "Registre todos los campos", 5, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.WARNING).setVisible(true);
        } else {
            funciones.funcionesVentas.guardarVentasServicio();
            
            new rojerusan.RSNotifyAnimated("Venta exitosa!", "Se ha completado la venta", 5, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
            funciones.funcionesOrdenServicios.FinalizarOrden(idOrdenSer.getText());
        try {
            JasperReport jr = (JasperReport) JRLoader.loadObject(getClass().getResource("/reportes/FacturaServicio.jasper"));
            //System.out.println("Id Alumno: ");
            Map parametro = new HashMap();
                parametro.put("IDFacturaVen", idVentaSer.getText()); 
                parametro.put("IMAGEN", getClass().getResourceAsStream("/imagenes/FacturaProducto.png"));
            JasperPrint jp = JasperFillManager.fillReport(jr, parametro, conexionActual);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);
            jv.setTitle("Factura Servicio");
        } catch (JRException ex) {
             System.err.println("Error: "+ex.getMessage());
    }
        
        this.dispose();
        }
           // new rojerusan.RSNotifyAnimated("ERROR", "No se puede realizar la venta", 5, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);
        }
        
        
    }//GEN-LAST:event_botonRegistrarVentaSerActionPerformed

    private void botonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioActionPerformed
       VerVentasSerProd f = new VerVentasSerProd(new JFrame(), true);
       f.setVisible(true);

    }//GEN-LAST:event_botonInventarioActionPerformed

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        Calcular();
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void botonEliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarServicioActionPerformed
        int fila = tablaVentaServicios.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tablaVentaServicios.getModel();
        modelo.removeRow(fila);
        rSPopuMenu1.setVisible(false);
    }//GEN-LAST:event_botonEliminarServicioActionPerformed

    private void botonEliminarProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarProducActionPerformed
        int fila = tablaVentaProductos.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) tablaVentaProductos.getModel();
        modelo.removeRow(fila);
        rSPopuMenu2.setVisible(false);
    }//GEN-LAST:event_botonEliminarProducActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EliminarProduc;
    private javax.swing.JPanel EliminarServicio;
    public static javax.swing.JLabel IdCliente;
    private rojerusan.RSButtonHover botonCalcular;
    private rojerusan.RSButtonHover botonClientes;
    private rojerusan.RSButtonHover botonEliminarProduc;
    private rojerusan.RSButtonHover botonEliminarServicio;
    private rojerusan.RSButtonHover botonInventario;
    private rojerusan.RSButtonHover botonRegistrarVentaSer;
    public static javax.swing.JTextField dateSeleccion;
    public static javax.swing.JLabel idDetVentaSer;
    public static javax.swing.JLabel idOrdenSer;
    public static javax.swing.JLabel idVentaSer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblTotal2;
    private rojerusan.RSPopuMenu rSPopuMenu1;
    private rojerusan.RSPopuMenu rSPopuMenu2;
    public static rojerusan.RSTableMetro tablaVentaProductos;
    public static rojerusan.RSTableMetro tablaVentaServicios;
    public static javax.swing.JTextField txtCodigoSer;
    public static javax.swing.JTextField txtSubTotal;
    public static javax.swing.JTextField txtTotalGen;
    public static javax.swing.JTextField txtTotalImpuesto;
    // End of variables declaration//GEN-END:variables
}
