/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import funciones.sentenciasTiposServicios;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import rojerusan.RSNotifyAnimated;

/**
 *
 * @author SailorSakura
 */
public class TiposServicios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TiposServicios
     */
    public TiposServicios() {
        initComponents();
        funciones.funcionesTiposServicios.setListar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botonAgregarTiposServicios = new rojerusan.RSButtonHover();
        botonModificarTiposServicios = new rojerusan.RSButtonHover();
        botonEliminarTiposServicios = new rojerusan.RSButtonHover();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaServicio = new rojerusan.RSTableMetro();
        jLabel7 = new javax.swing.JLabel();
        txtBuscarServicio = new rojerusan.RSMetroTextFullPlaceHolder();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-cerrar2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        botonAgregarTiposServicios.setBackground(new java.awt.Color(11, 11, 11));
        botonAgregarTiposServicios.setText("Agregar servicio");
        botonAgregarTiposServicios.setColorHover(new java.awt.Color(240, 4, 7));
        botonAgregarTiposServicios.setMaximumSize(new java.awt.Dimension(91, 25));
        botonAgregarTiposServicios.setMinimumSize(new java.awt.Dimension(91, 25));
        botonAgregarTiposServicios.setName("botonAgregarTiposServicios"); // NOI18N
        botonAgregarTiposServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarTiposServiciosActionPerformed(evt);
            }
        });

        botonModificarTiposServicios.setBackground(new java.awt.Color(11, 11, 11));
        botonModificarTiposServicios.setText("Modificar Servicio");
        botonModificarTiposServicios.setColorHover(new java.awt.Color(240, 4, 7));
        botonModificarTiposServicios.setMaximumSize(new java.awt.Dimension(91, 25));
        botonModificarTiposServicios.setMinimumSize(new java.awt.Dimension(91, 25));
        botonModificarTiposServicios.setName("botonModificarTiposServicios"); // NOI18N
        botonModificarTiposServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarTiposServiciosActionPerformed(evt);
            }
        });

        botonEliminarTiposServicios.setBackground(new java.awt.Color(11, 11, 11));
        botonEliminarTiposServicios.setText("Eliminar Servicio");
        botonEliminarTiposServicios.setColorHover(new java.awt.Color(240, 4, 7));
        botonEliminarTiposServicios.setMaximumSize(new java.awt.Dimension(91, 25));
        botonEliminarTiposServicios.setMinimumSize(new java.awt.Dimension(91, 25));
        botonEliminarTiposServicios.setName("botonEliminarTiposServicios"); // NOI18N
        botonEliminarTiposServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarTiposServiciosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("LISTADO DE SERVICIOS");

        tablaServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Servicio", "Precio", "Impuesto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaServicio.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaServicio.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaServicio.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaServicio.setName("tablaServicio"); // NOI18N
        tablaServicio.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane1.setViewportView(tablaServicio);
        if (tablaServicio.getColumnModel().getColumnCount() > 0) {
            tablaServicio.getColumnModel().getColumn(0).setMinWidth(0);
            tablaServicio.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Buscar:");

        txtBuscarServicio.setForeground(new java.awt.Color(11, 11, 11));
        txtBuscarServicio.setBorderColor(new java.awt.Color(11, 11, 11));
        txtBuscarServicio.setBotonColor(new java.awt.Color(240, 4, 7));
        txtBuscarServicio.setName("txtBuscarServicio"); // NOI18N
        txtBuscarServicio.setPhColor(new java.awt.Color(0, 0, 0));
        txtBuscarServicio.setPlaceholder("");
        txtBuscarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarServicioActionPerformed(evt);
            }
        });
        txtBuscarServicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarServicioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(195, 195, 195)
                            .addComponent(jLabel5))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(botonAgregarTiposServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(botonModificarTiposServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(botonEliminarTiposServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminarTiposServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificarTiposServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregarTiposServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void botonAgregarTiposServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarTiposServiciosActionPerformed
        AgregarTiposServicios b = new AgregarTiposServicios(new JFrame(), true);
        b.show();
    }//GEN-LAST:event_botonAgregarTiposServiciosActionPerformed

    private void botonModificarTiposServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarTiposServiciosActionPerformed
        int a = tablaServicio.getSelectedRow();
        if (a > -1){
        int fila = tablaServicio.getSelectedRow();
        Frame f = JOptionPane.getFrameForComponent(this);
        ModificarTiposServicios dialog = new ModificarTiposServicios(f, true);
        dialog.txtNombreServicio.setText(tablaServicio.getValueAt(fila, 1).toString());
        dialog.txtPrecioMano.setText(tablaServicio.getValueAt(fila, 2).toString());
        dialog.comboImpuestoUpdate.setSelectedItem(tablaServicio.getValueAt(fila, 3).toString());
        dialog.idTiposServicio.setText(tablaServicio.getValueAt(fila, 0).toString());
        dialog.show();
        } else {
            new rojerusan.RSNotifyAnimated("ERROR", "Seleccione uno", 5, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);

        }
    }//GEN-LAST:event_botonModificarTiposServiciosActionPerformed
String hora = "";
String fecha= "";
    private void botonEliminarTiposServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarTiposServiciosActionPerformed
            String tabla = "TIPOS SERVICIOS";
            String evento = "DELETE";
            hora = Principal.lblhora.getHora();
            fecha = Principal.lblfecha.getFecha();
        int b = tablaServicio.getSelectedRow();
        if (b > -1){
        int fila = tablaServicio.getSelectedRow();
        sentenciasTiposServicios s = new sentenciasTiposServicios();
        s.setId_tservicio(tablaServicio.getValueAt(fila, 0).toString());
        if (JOptionPane.showConfirmDialog(this, "Desea eliminar registro?", "",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
            if (funciones.funcionesTiposServicios.isDelete(s)){
                new rojerusan.RSNotifyAnimated("EXITO", "Se ha eliminado con exito", 5, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.SUCCESS).setVisible(true);
                funciones.funcionesTiposServicios.setListar("");
                funciones.funcionesTiposServicios.extraerIDMaxTIPO();
                funciones.funcionesAuditoria.auditoria(fecha, hora, evento, tabla, login.funcionesLogin.idFuncionario);
            }
        }
        } else {
            new rojerusan.RSNotifyAnimated("ERROR", "Seleccione uno", 5, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);

        }
    }//GEN-LAST:event_botonEliminarTiposServiciosActionPerformed

    private void txtBuscarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarServicioActionPerformed

    private void txtBuscarServicioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarServicioKeyReleased
        librerias.Mayusculas.convertiraMayusculasEnJtextfield(txtBuscarServicio);
        funciones.funcionesTiposServicios.setListar(this.txtBuscarServicio.getText());
    }//GEN-LAST:event_txtBuscarServicioKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover botonAgregarTiposServicios;
    private rojerusan.RSButtonHover botonEliminarTiposServicios;
    private rojerusan.RSButtonHover botonModificarTiposServicios;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static rojerusan.RSTableMetro tablaServicio;
    private rojerusan.RSMetroTextFullPlaceHolder txtBuscarServicio;
    // End of variables declaration//GEN-END:variables
}
