/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import funciones.sentenciasUsuarios;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import rojerusan.RSNotifyAnimated;
import rojerusan.RSNotifyFade;

/**
 *
 * @author SailorSakura
 */
public class Usuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        funciones.funcionesUsuarios.setListar("");
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new rojerusan.RSTableMetro();
        botonAgregarUsuario = new rojerusan.RSButtonHover();
        botonModificarUsuario = new rojerusan.RSButtonHover();
        botonEliminarUsuario = new rojerusan.RSButtonHover();
        txtBuscarUsuarios = new rojerusan.RSMetroTextFullPlaceHolder();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(748, 561));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-cerrar2.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("LISTADO DE USUARIOS");

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User", "Password", "Funcionario", "Tipo de Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuarios.setColorBackgoundHead(new java.awt.Color(240, 4, 7));
        tablaUsuarios.setColorFilasForeground1(new java.awt.Color(240, 4, 7));
        tablaUsuarios.setColorFilasForeground2(new java.awt.Color(242, 134, 130));
        tablaUsuarios.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tablaUsuarios.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tablaUsuarios.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablaUsuarios.setName("tablaUsuarios"); // NOI18N
        tablaUsuarios.setSelectionBackground(new java.awt.Color(240, 198, 196));
        jScrollPane1.setViewportView(tablaUsuarios);
        if (tablaUsuarios.getColumnModel().getColumnCount() > 0) {
            tablaUsuarios.getColumnModel().getColumn(0).setMinWidth(0);
            tablaUsuarios.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        botonAgregarUsuario.setBackground(new java.awt.Color(11, 11, 11));
        botonAgregarUsuario.setText("Agregar Usuario");
        botonAgregarUsuario.setColorHover(new java.awt.Color(240, 4, 7));
        botonAgregarUsuario.setMaximumSize(new java.awt.Dimension(91, 25));
        botonAgregarUsuario.setMinimumSize(new java.awt.Dimension(91, 25));
        botonAgregarUsuario.setName("botonAgregarUsuario"); // NOI18N
        botonAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarUsuarioActionPerformed(evt);
            }
        });

        botonModificarUsuario.setBackground(new java.awt.Color(11, 11, 11));
        botonModificarUsuario.setText("Modificar Usuario");
        botonModificarUsuario.setColorHover(new java.awt.Color(240, 4, 7));
        botonModificarUsuario.setMaximumSize(new java.awt.Dimension(91, 25));
        botonModificarUsuario.setMinimumSize(new java.awt.Dimension(91, 25));
        botonModificarUsuario.setName("botonModificarUsuario"); // NOI18N
        botonModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarUsuarioActionPerformed(evt);
            }
        });

        botonEliminarUsuario.setBackground(new java.awt.Color(11, 11, 11));
        botonEliminarUsuario.setText("Eliminar Usuario");
        botonEliminarUsuario.setColorHover(new java.awt.Color(240, 4, 7));
        botonEliminarUsuario.setMaximumSize(new java.awt.Dimension(91, 25));
        botonEliminarUsuario.setMinimumSize(new java.awt.Dimension(91, 25));
        botonEliminarUsuario.setName("botonEliminarUsuario"); // NOI18N
        botonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarUsuarioActionPerformed(evt);
            }
        });

        txtBuscarUsuarios.setForeground(new java.awt.Color(11, 11, 11));
        txtBuscarUsuarios.setBorderColor(new java.awt.Color(11, 11, 11));
        txtBuscarUsuarios.setBotonColor(new java.awt.Color(240, 4, 7));
        txtBuscarUsuarios.setName("txtBuscarUsuarios"); // NOI18N
        txtBuscarUsuarios.setPhColor(new java.awt.Color(0, 0, 0));
        txtBuscarUsuarios.setPlaceholder("");
        txtBuscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarUsuariosActionPerformed(evt);
            }
        });
        txtBuscarUsuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarUsuariosKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Buscar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel2)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void botonAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarUsuarioActionPerformed
        AgregarUsuario b = new AgregarUsuario(new JFrame(), true);
        b.show();
    }//GEN-LAST:event_botonAgregarUsuarioActionPerformed

    private void txtBuscarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarUsuariosActionPerformed

    private void botonModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarUsuarioActionPerformed
        int a = tablaUsuarios.getSelectedRow();
        if (a > -1){
        int fila = tablaUsuarios.getSelectedRow();
        Frame f = JOptionPane.getFrameForComponent(this);
        ModificarUsuario dialog = new ModificarUsuario(f, true);
        dialog.txtNombreUsuario.setText(tablaUsuarios.getValueAt(fila, 1).toString());
        dialog.txtPass.setText(tablaUsuarios.getValueAt(fila, 2).toString());
        dialog.comboFuncionarioUpdate.setSelectedItem(tablaUsuarios.getValueAt(fila, 3).toString());
        dialog.comboTipoUpdate.setSelectedItem(tablaUsuarios.getValueAt(fila, 4).toString());
        dialog.txtIdUsuario.setText(tablaUsuarios.getValueAt(fila, 0).toString());
        dialog.show();
        } else {
            new rojerusan.RSNotifyAnimated("ERROR", "Seleccione uno", 5, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);

        }
    }//GEN-LAST:event_botonModificarUsuarioActionPerformed
String hora = "";
String fecha= "";
    private void botonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioActionPerformed
        String tabla = "USUARIO";
            String evento = "DELETE";
            hora = Principal.lblhora.getHora();
            fecha = Principal.lblfecha.getFecha();
        int b = tablaUsuarios.getSelectedRow();
        if (b > -1){
        int fila = tablaUsuarios.getSelectedRow();
        sentenciasUsuarios s = new sentenciasUsuarios();
        s.setId_usuario(tablaUsuarios.getValueAt(fila, 0).toString());
        if (JOptionPane.showConfirmDialog(this, "Desea eliminar registro?", "",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION){
            if (funciones.funcionesUsuarios.isDelete(s)){
                funciones.funcionesAuditoria.auditoria(fecha, hora, evento, tabla, login.funcionesLogin.idFuncionario);
                vistas.AgregarUsuario.txtIdUsuario.setText(funciones.funcionesUsuarios.extraerIDMaxUSU());
                funciones.funcionesUsuarios.setListar("");
                new rojerusan.RSNotifyFade("EXITO", "Se la eliminado el usuario", 5, RSNotifyFade.PositionNotify.TopLef, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
            }
        }
        } else {
            new rojerusan.RSNotifyAnimated("ERROR", "Seleccione uno", 5, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.ERROR).setVisible(true);

        }
    }//GEN-LAST:event_botonEliminarUsuarioActionPerformed

    private void txtBuscarUsuariosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarUsuariosKeyReleased
        librerias.Mayusculas.convertiraMayusculasEnJtextfield(txtBuscarUsuarios);
        funciones.funcionesUsuarios.setListar(txtBuscarUsuarios.getText());
    }//GEN-LAST:event_txtBuscarUsuariosKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover botonAgregarUsuario;
    private rojerusan.RSButtonHover botonEliminarUsuario;
    private rojerusan.RSButtonHover botonModificarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static rojerusan.RSTableMetro tablaUsuarios;
    private rojerusan.RSMetroTextFullPlaceHolder txtBuscarUsuarios;
    // End of variables declaration//GEN-END:variables
}
